// Code generated by genrouting. DO NOT EDIT.
package catalogservice

import (
	"context"

	"github.com/milvus-io/milvus-proto/go-api/v3/milvuspb"
	"github.com/milvus-io/milvus/internal/metastore/model"
	"github.com/milvus-io/milvus/pkg/v3/proto/internalpb"
	"github.com/milvus-io/milvus/pkg/v3/proto/rootcoordpb"
	"github.com/milvus-io/milvus/pkg/v3/streaming/util/message"
	"github.com/milvus-io/milvus/pkg/v3/util/typeutil"
)

func (r *routingMetaTable) CheckIfAddCredential(ctx context.Context, req *internalpb.CredentialInfo) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfAddCredential(ctx, req)
}

func (r *routingMetaTable) CheckIfUpdateCredential(ctx context.Context, req *internalpb.CredentialInfo) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfUpdateCredential(ctx, req)
}

func (r *routingMetaTable) CheckIfDeleteCredential(ctx context.Context, req *milvuspb.DeleteCredentialRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfDeleteCredential(ctx, req)
}

func (r *routingMetaTable) CheckIfCreateRole(ctx context.Context, req *milvuspb.CreateRoleRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfCreateRole(ctx, req)
}

func (r *routingMetaTable) CheckIfAlterRole(ctx context.Context, req *milvuspb.AlterRoleRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfAlterRole(ctx, req)
}

func (r *routingMetaTable) CheckIfDropRole(ctx context.Context, in *milvuspb.DropRoleRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfDropRole(ctx, in)
}

func (r *routingMetaTable) CheckIfOperateUserRole(ctx context.Context, req *milvuspb.OperateUserRoleRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfOperateUserRole(ctx, req)
}

func (r *routingMetaTable) CheckIfPrivilegeGroupCreatable(ctx context.Context, req *milvuspb.CreatePrivilegeGroupRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfPrivilegeGroupCreatable(ctx, req)
}

func (r *routingMetaTable) CheckIfPrivilegeGroupAlterable(ctx context.Context, req *milvuspb.OperatePrivilegeGroupRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfPrivilegeGroupAlterable(ctx, req)
}

func (r *routingMetaTable) CheckIfPrivilegeGroupDropable(ctx context.Context, req *milvuspb.DropPrivilegeGroupRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfPrivilegeGroupDropable(ctx, req)
}

func (r *routingMetaTable) CheckIfRBACRestorable(ctx context.Context, req *milvuspb.RestoreRBACMetaRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfRBACRestorable(ctx, req)
}

func (r *routingMetaTable) CheckIfDatabaseCreatable(ctx context.Context, req *milvuspb.CreateDatabaseRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfDatabaseCreatable(ctx, req)
}

func (r *routingMetaTable) CheckIfDatabaseDroppable(ctx context.Context, req *milvuspb.DropDatabaseRequest) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfDatabaseDroppable(ctx, req)
}

func (r *routingMetaTable) CheckIfAliasCreatable(ctx context.Context, dbName string, alias string, collectionName string) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfAliasCreatable(ctx, dbName, alias, collectionName)
}

func (r *routingMetaTable) CheckIfAliasAlterable(ctx context.Context, dbName string, alias string, collectionName string) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfAliasAlterable(ctx, dbName, alias, collectionName)
}

func (r *routingMetaTable) CheckIfAliasDroppable(ctx context.Context, dbName string, alias string) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfAliasDroppable(ctx, dbName, alias)
}

func (r *routingMetaTable) GetDatabaseByID(ctx context.Context, dbID int64, ts typeutil.Timestamp) (res0 *model.Database, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.GetDatabaseByID(ctx, dbID, ts)
}

func (r *routingMetaTable) GetDatabaseByName(ctx context.Context, dbName string, ts typeutil.Timestamp) (res0 *model.Database, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.GetDatabaseByName(ctx, dbName, ts)
}

func (r *routingMetaTable) CreateDatabase(ctx context.Context, db *model.Database, ts typeutil.Timestamp) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CreateDatabase(ctx, db, ts)
}

func (r *routingMetaTable) DropDatabase(ctx context.Context, dbName string, ts typeutil.Timestamp) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DropDatabase(ctx, dbName, ts)
}

func (r *routingMetaTable) ListDatabases(ctx context.Context, ts typeutil.Timestamp) (res0 []*model.Database, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.ListDatabases(ctx, ts)
}

func (r *routingMetaTable) AlterDatabase(ctx context.Context, newDB *model.Database, ts typeutil.Timestamp) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AlterDatabase(ctx, newDB, ts)
}

func (r *routingMetaTable) AddCollection(ctx context.Context, coll *model.Collection) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AddCollection(ctx, coll)
}

func (r *routingMetaTable) DropCollection(ctx context.Context, collectionID typeutil.UniqueID, ts typeutil.Timestamp) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DropCollection(ctx, collectionID, ts)
}

func (r *routingMetaTable) RemoveCollection(ctx context.Context, collectionID typeutil.UniqueID, ts typeutil.Timestamp) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.RemoveCollection(ctx, collectionID, ts)
}

func (r *routingMetaTable) GetCollectionID(ctx context.Context, dbName string, collectionName string) (res0 typeutil.UniqueID) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.GetCollectionID(ctx, dbName, collectionName)
}

func (r *routingMetaTable) GetCollectionByName(ctx context.Context, dbName string, collectionName string, ts typeutil.Timestamp, allowUnavailable bool) (res0 *model.Collection, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.GetCollectionByName(ctx, dbName, collectionName, ts, allowUnavailable)
}

func (r *routingMetaTable) GetCollectionByID(ctx context.Context, dbName string, collectionID typeutil.UniqueID, ts typeutil.Timestamp, allowUnavailable bool) (res0 *model.Collection, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.GetCollectionByID(ctx, dbName, collectionID, ts, allowUnavailable)
}

func (r *routingMetaTable) GetCollectionByIDWithMaxTs(ctx context.Context, collectionID typeutil.UniqueID) (res0 *model.Collection, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.GetCollectionByIDWithMaxTs(ctx, collectionID)
}

func (r *routingMetaTable) ListCollections(ctx context.Context, dbName string, ts typeutil.Timestamp, onlyAvail bool) (res0 []*model.Collection, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.ListCollections(ctx, dbName, ts, onlyAvail)
}

func (r *routingMetaTable) ListAllAvailCollections(ctx context.Context) (res0 map[int64][]int64) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.ListAllAvailCollections(ctx)
}

func (r *routingMetaTable) ListAllAvailPartitions(ctx context.Context) (res0 map[int64]map[int64][]int64) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.ListAllAvailPartitions(ctx)
}

func (r *routingMetaTable) ListCollectionPhysicalChannels(ctx context.Context) (res0 map[typeutil.UniqueID][]string) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.ListCollectionPhysicalChannels(ctx)
}

func (r *routingMetaTable) GetCollectionVirtualChannels(ctx context.Context, colID int64) (res0 []string) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.GetCollectionVirtualChannels(ctx, colID)
}

func (r *routingMetaTable) GetPChannelInfo(ctx context.Context, pchannel string) (res0 *rootcoordpb.GetPChannelInfoResponse) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.GetPChannelInfo(ctx, pchannel)
}

func (r *routingMetaTable) AddPartition(ctx context.Context, partition *model.Partition) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AddPartition(ctx, partition)
}

func (r *routingMetaTable) GetPartitionIDByName(collectionID int64, partitionName string) (res0 int64, res1 bool) {
	m, rerr := r.resolve(context.Background())
	if rerr != nil {
		return
	}
	return m.GetPartitionIDByName(collectionID, partitionName)
}

func (r *routingMetaTable) DropPartition(ctx context.Context, collectionID typeutil.UniqueID, partitionID typeutil.UniqueID, ts typeutil.Timestamp) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DropPartition(ctx, collectionID, partitionID, ts)
}

func (r *routingMetaTable) RemovePartition(ctx context.Context, collectionID typeutil.UniqueID, partitionID typeutil.UniqueID, ts typeutil.Timestamp) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.RemovePartition(ctx, collectionID, partitionID, ts)
}

func (r *routingMetaTable) AlterAlias(ctx context.Context, result message.BroadcastResultAlterAliasMessageV2) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AlterAlias(ctx, result)
}

func (r *routingMetaTable) DropAlias(ctx context.Context, result message.BroadcastResultDropAliasMessageV2) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DropAlias(ctx, result)
}

func (r *routingMetaTable) DescribeAlias(ctx context.Context, dbName string, alias string, ts typeutil.Timestamp) (res0 string, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.DescribeAlias(ctx, dbName, alias, ts)
}

func (r *routingMetaTable) ListAliases(ctx context.Context, dbName string, collectionName string, ts typeutil.Timestamp) (res0 []string, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.ListAliases(ctx, dbName, collectionName, ts)
}

func (r *routingMetaTable) AlterCollection(ctx context.Context, result message.BroadcastResultAlterCollectionMessageV2) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AlterCollection(ctx, result)
}

func (r *routingMetaTable) BeginTruncateCollection(ctx context.Context, collectionID typeutil.UniqueID) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.BeginTruncateCollection(ctx, collectionID)
}

func (r *routingMetaTable) TruncateCollection(ctx context.Context, result message.BroadcastResultTruncateCollectionMessageV2) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.TruncateCollection(ctx, result)
}

func (r *routingMetaTable) CheckIfCollectionRenamable(ctx context.Context, dbName string, oldName string, newDBName string, newName string) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CheckIfCollectionRenamable(ctx, dbName, oldName, newDBName, newName)
}

func (r *routingMetaTable) GetGeneralCount(ctx context.Context) (res0 int) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.GetGeneralCount(ctx)
}

func (r *routingMetaTable) IsAlias(ctx context.Context, db, name string) (res0 bool) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.IsAlias(ctx, db, name)
}

func (r *routingMetaTable) ListAliasesByID(ctx context.Context, collID typeutil.UniqueID) (res0 []string) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.ListAliasesByID(ctx, collID)
}

func (r *routingMetaTable) GetCredential(ctx context.Context, username string) (res0 *internalpb.CredentialInfo, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.GetCredential(ctx, username)
}

func (r *routingMetaTable) InitCredential(ctx context.Context) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.InitCredential(ctx)
}

func (r *routingMetaTable) DeleteCredential(ctx context.Context, result message.BroadcastResultDropUserMessageV2) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DeleteCredential(ctx, result)
}

func (r *routingMetaTable) AlterCredential(ctx context.Context, result message.BroadcastResultAlterUserMessageV2) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AlterCredential(ctx, result)
}

func (r *routingMetaTable) ListCredentialUsernames(ctx context.Context) (res0 *milvuspb.ListCredUsersResponse, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.ListCredentialUsernames(ctx)
}

func (r *routingMetaTable) CreateRole(ctx context.Context, tenant string, entity *milvuspb.RoleEntity) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CreateRole(ctx, tenant, entity)
}

func (r *routingMetaTable) AlterRole(ctx context.Context, tenant string, entity *milvuspb.RoleEntity) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AlterRole(ctx, tenant, entity)
}

func (r *routingMetaTable) DropRole(ctx context.Context, tenant string, roleName string) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DropRole(ctx, tenant, roleName)
}

func (r *routingMetaTable) OperateUserRole(ctx context.Context, tenant string, userEntity *milvuspb.UserEntity, roleEntity *milvuspb.RoleEntity, operateType milvuspb.OperateUserRoleType) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.OperateUserRole(ctx, tenant, userEntity, roleEntity, operateType)
}

func (r *routingMetaTable) SelectRole(ctx context.Context, tenant string, entity *milvuspb.RoleEntity, includeUserInfo bool) (res0 []*milvuspb.RoleResult, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.SelectRole(ctx, tenant, entity, includeUserInfo)
}

func (r *routingMetaTable) SelectUser(ctx context.Context, tenant string, entity *milvuspb.UserEntity, includeRoleInfo bool) (res0 []*milvuspb.UserResult, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.SelectUser(ctx, tenant, entity, includeRoleInfo)
}

func (r *routingMetaTable) OperatePrivilege(ctx context.Context, tenant string, entity *milvuspb.GrantEntity, operateType milvuspb.OperatePrivilegeType) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.OperatePrivilege(ctx, tenant, entity, operateType)
}

func (r *routingMetaTable) SelectGrant(ctx context.Context, tenant string, entity *milvuspb.GrantEntity) (res0 []*milvuspb.GrantEntity, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.SelectGrant(ctx, tenant, entity)
}

func (r *routingMetaTable) DropGrant(ctx context.Context, tenant string, role *milvuspb.RoleEntity) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DropGrant(ctx, tenant, role)
}

func (r *routingMetaTable) ListPolicy(ctx context.Context, tenant string) (res0 []*milvuspb.GrantEntity, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.ListPolicy(ctx, tenant)
}

func (r *routingMetaTable) ListUserRole(ctx context.Context, tenant string) (res0 []string, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.ListUserRole(ctx, tenant)
}

func (r *routingMetaTable) BackupRBAC(ctx context.Context, tenant string) (res0 *milvuspb.RBACMeta, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.BackupRBAC(ctx, tenant)
}

func (r *routingMetaTable) RestoreRBAC(ctx context.Context, tenant string, meta *milvuspb.RBACMeta) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.RestoreRBAC(ctx, tenant, meta)
}

func (r *routingMetaTable) IsCustomPrivilegeGroup(ctx context.Context, groupName string) (res0 bool, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.IsCustomPrivilegeGroup(ctx, groupName)
}

func (r *routingMetaTable) CreatePrivilegeGroup(ctx context.Context, groupName string) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.CreatePrivilegeGroup(ctx, groupName)
}

func (r *routingMetaTable) DropPrivilegeGroup(ctx context.Context, groupName string) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.DropPrivilegeGroup(ctx, groupName)
}

func (r *routingMetaTable) ListPrivilegeGroups(ctx context.Context) (res0 []*milvuspb.PrivilegeGroupInfo, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.ListPrivilegeGroups(ctx)
}

func (r *routingMetaTable) OperatePrivilegeGroup(ctx context.Context, groupName string, privileges []*milvuspb.PrivilegeEntity, operateType milvuspb.OperatePrivilegeGroupType) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.OperatePrivilegeGroup(ctx, groupName, privileges, operateType)
}

func (r *routingMetaTable) GetPrivilegeGroupRoles(ctx context.Context, groupName string) (res0 []*milvuspb.RoleEntity, res1 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res1 = rerr
		return
	}
	return m.GetPrivilegeGroupRoles(ctx, groupName)
}

func (r *routingMetaTable) AddFileResource(ctx context.Context, resource *internalpb.FileResourceInfo) (res0 error) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.AddFileResource(ctx, resource)
}

func (r *routingMetaTable) RemoveFileResource(ctx context.Context, name string) (res0 error, res1 bool) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.RemoveFileResource(ctx, name)
}

func (r *routingMetaTable) ListFileResource(ctx context.Context) (res0 []*internalpb.FileResourceInfo, res1 uint64) {
	m, rerr := r.resolve(ctx)
	if rerr != nil {
		return
	}
	return m.ListFileResource(ctx)
}

func (r *routingMetaTable) IncFileResourceRefCnt(ids []int64) (res0 error) {
	m, rerr := r.resolve(context.Background())
	if rerr != nil {
		res0 = rerr
		return
	}
	return m.IncFileResourceRefCnt(ids)
}

func (r *routingMetaTable) DecFileResourceRefCnt(ids []int64) {
	m, rerr := r.resolve(context.Background())
	if rerr != nil {
		return
	}
	m.DecFileResourceRefCnt(ids)
}

func (r *routingMetaTable) RecoverFileResourceRefCnt(pendingCollections map[int64][]int64) {
	m, rerr := r.resolve(context.Background())
	if rerr != nil {
		return
	}
	m.RecoverFileResourceRefCnt(pendingCollections)
}
