// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_migration.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // logical key (no backend rootPath)
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KvEntry) Reset() {
	*x = KvEntry{}
	mi := &file_catalog_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvEntry) ProtoMessage() {}

func (x *KvEntry) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvEntry.ProtoReflect.Descriptor instead.
func (*KvEntry) Descriptor() ([]byte, []int) {
	return file_catalog_migration_proto_rawDescGZIP(), []int{0}
}

func (x *KvEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BulkImportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string     `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // cluster-id; selects the destination TiKV prefix
	Entries   []*KvEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *BulkImportRequest) Reset() {
	*x = BulkImportRequest{}
	mi := &file_catalog_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportRequest) ProtoMessage() {}

func (x *BulkImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportRequest.ProtoReflect.Descriptor instead.
func (*BulkImportRequest) Descriptor() ([]byte, []int) {
	return file_catalog_migration_proto_rawDescGZIP(), []int{1}
}

func (x *BulkImportRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *BulkImportRequest) GetEntries() []*KvEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BulkImportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Imported int64            `protobuf:"varint,2,opt,name=imported,proto3" json:"imported,omitempty"`
}

func (x *BulkImportResponse) Reset() {
	*x = BulkImportResponse{}
	mi := &file_catalog_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportResponse) ProtoMessage() {}

func (x *BulkImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportResponse.ProtoReflect.Descriptor instead.
func (*BulkImportResponse) Descriptor() ([]byte, []int) {
	return file_catalog_migration_proto_rawDescGZIP(), []int{2}
}

func (x *BulkImportResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BulkImportResponse) GetImported() int64 {
	if x != nil {
		return x.Imported
	}
	return 0
}

type VerifyMismatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // missing-in-dst | missing-in-src | value-differs
}

func (x *VerifyMismatch) Reset() {
	*x = VerifyMismatch{}
	mi := &file_catalog_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMismatch) ProtoMessage() {}

func (x *VerifyMismatch) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMismatch.ProtoReflect.Descriptor instead.
func (*VerifyMismatch) Descriptor() ([]byte, []int) {
	return file_catalog_migration_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyMismatch) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VerifyMismatch) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VerifyImportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string     `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Roots     []string   `protobuf:"bytes,2,rep,name=roots,proto3" json:"roots,omitempty"`     // prefixes that define the migrated keyspace in the dest
	Entries   []*KvEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"` // a fresh source snapshot to compare the dest against
}

func (x *VerifyImportRequest) Reset() {
	*x = VerifyImportRequest{}
	mi := &file_catalog_migration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImportRequest) ProtoMessage() {}

func (x *VerifyImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_migration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImportRequest.ProtoReflect.Descriptor instead.
func (*VerifyImportRequest) Descriptor() ([]byte, []int) {
	return file_catalog_migration_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyImportRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *VerifyImportRequest) GetRoots() []string {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *VerifyImportRequest) GetEntries() []*KvEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type VerifyImportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     *commonpb.Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Mismatches []*VerifyMismatch `protobuf:"bytes,2,rep,name=mismatches,proto3" json:"mismatches,omitempty"`
}

func (x *VerifyImportResponse) Reset() {
	*x = VerifyImportResponse{}
	mi := &file_catalog_migration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImportResponse) ProtoMessage() {}

func (x *VerifyImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_migration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImportResponse.ProtoReflect.Descriptor instead.
func (*VerifyImportResponse) Descriptor() ([]byte, []int) {
	return file_catalog_migration_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyImportResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VerifyImportResponse) GetMismatches() []*VerifyMismatch {
	if x != nil {
		return x.Mismatches
	}
	return nil
}

var File_catalog_migration_proto protoreflect.FileDescriptor

var file_catalog_migration_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a,
	0x07, 0x4b, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x6a, 0x0a, 0x11, 0x42, 0x75, 0x6c, 0x6b, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x4b, 0x76, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x65, 0x0a, 0x12,
	0x42, 0x75, 0x6c, 0x6b, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x22, 0x3a, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d, 0x69, 0x73,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x82, 0x01, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x2e, 0x4b, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x44, 0x0a, 0x0a, 0x6d, 0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x4d, 0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x0a, 0x6d, 0x69,
	0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2d, 0x69, 0x6f,
	0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x33, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_migration_proto_rawDescOnce sync.Once
	file_catalog_migration_proto_rawDescData = file_catalog_migration_proto_rawDesc
)

func file_catalog_migration_proto_rawDescGZIP() []byte {
	file_catalog_migration_proto_rawDescOnce.Do(func() {
		file_catalog_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_migration_proto_rawDescData)
	})
	return file_catalog_migration_proto_rawDescData
}

var file_catalog_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_catalog_migration_proto_goTypes = []any{
	(*KvEntry)(nil),              // 0: milvus.proto.catalog.KvEntry
	(*BulkImportRequest)(nil),    // 1: milvus.proto.catalog.BulkImportRequest
	(*BulkImportResponse)(nil),   // 2: milvus.proto.catalog.BulkImportResponse
	(*VerifyMismatch)(nil),       // 3: milvus.proto.catalog.VerifyMismatch
	(*VerifyImportRequest)(nil),  // 4: milvus.proto.catalog.VerifyImportRequest
	(*VerifyImportResponse)(nil), // 5: milvus.proto.catalog.VerifyImportResponse
	(*commonpb.Status)(nil),      // 6: milvus.proto.common.Status
}
var file_catalog_migration_proto_depIdxs = []int32{
	0, // 0: milvus.proto.catalog.BulkImportRequest.entries:type_name -> milvus.proto.catalog.KvEntry
	6, // 1: milvus.proto.catalog.BulkImportResponse.status:type_name -> milvus.proto.common.Status
	0, // 2: milvus.proto.catalog.VerifyImportRequest.entries:type_name -> milvus.proto.catalog.KvEntry
	6, // 3: milvus.proto.catalog.VerifyImportResponse.status:type_name -> milvus.proto.common.Status
	3, // 4: milvus.proto.catalog.VerifyImportResponse.mismatches:type_name -> milvus.proto.catalog.VerifyMismatch
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_catalog_migration_proto_init() }
func file_catalog_migration_proto_init() {
	if File_catalog_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_migration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_migration_proto_goTypes,
		DependencyIndexes: file_catalog_migration_proto_depIdxs,
		MessageInfos:      file_catalog_migration_proto_msgTypes,
	}.Build()
	File_catalog_migration_proto = out.File
	file_catalog_migration_proto_rawDesc = nil
	file_catalog_migration_proto_goTypes = nil
	file_catalog_migration_proto_depIdxs = nil
}
