// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_alias.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	messagespb "github.com/milvus-io/milvus/pkg/v3/proto/messagespb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlterAlias rebuilds BroadcastResultAlterAliasMessageV2 from header + time_tick.
type AlterAliasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *messagespb.AlterAliasMessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TimeTick uint64                              `protobuf:"varint,2,opt,name=time_tick,json=timeTick,proto3" json:"time_tick,omitempty"`
}

func (x *AlterAliasRequest) Reset() {
	*x = AlterAliasRequest{}
	mi := &file_catalog_alias_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterAliasRequest) ProtoMessage() {}

func (x *AlterAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterAliasRequest.ProtoReflect.Descriptor instead.
func (*AlterAliasRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{0}
}

func (x *AlterAliasRequest) GetHeader() *messagespb.AlterAliasMessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AlterAliasRequest) GetTimeTick() uint64 {
	if x != nil {
		return x.TimeTick
	}
	return 0
}

type AlterAliasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AlterAliasResponse) Reset() {
	*x = AlterAliasResponse{}
	mi := &file_catalog_alias_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterAliasResponse) ProtoMessage() {}

func (x *AlterAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterAliasResponse.ProtoReflect.Descriptor instead.
func (*AlterAliasResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{1}
}

func (x *AlterAliasResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// DropAlias rebuilds BroadcastResultDropAliasMessageV2 from header + time_tick.
type DropAliasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *messagespb.DropAliasMessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TimeTick uint64                             `protobuf:"varint,2,opt,name=time_tick,json=timeTick,proto3" json:"time_tick,omitempty"`
}

func (x *DropAliasRequest) Reset() {
	*x = DropAliasRequest{}
	mi := &file_catalog_alias_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropAliasRequest) ProtoMessage() {}

func (x *DropAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropAliasRequest.ProtoReflect.Descriptor instead.
func (*DropAliasRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{2}
}

func (x *DropAliasRequest) GetHeader() *messagespb.DropAliasMessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DropAliasRequest) GetTimeTick() uint64 {
	if x != nil {
		return x.TimeTick
	}
	return 0
}

type DropAliasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DropAliasResponse) Reset() {
	*x = DropAliasResponse{}
	mi := &file_catalog_alias_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropAliasResponse) ProtoMessage() {}

func (x *DropAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropAliasResponse.ProtoReflect.Descriptor instead.
func (*DropAliasResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{3}
}

func (x *DropAliasResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DescribeAliasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Alias  string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Ts     uint64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *DescribeAliasRequest) Reset() {
	*x = DescribeAliasRequest{}
	mi := &file_catalog_alias_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeAliasRequest) ProtoMessage() {}

func (x *DescribeAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeAliasRequest.ProtoReflect.Descriptor instead.
func (*DescribeAliasRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeAliasRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *DescribeAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DescribeAliasRequest) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type DescribeAliasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CollectionName string           `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
}

func (x *DescribeAliasResponse) Reset() {
	*x = DescribeAliasResponse{}
	mi := &file_catalog_alias_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeAliasResponse) ProtoMessage() {}

func (x *DescribeAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeAliasResponse.ProtoReflect.Descriptor instead.
func (*DescribeAliasResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeAliasResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DescribeAliasResponse) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type ListAliasesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName         string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName string `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Ts             uint64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *ListAliasesRequest) Reset() {
	*x = ListAliasesRequest{}
	mi := &file_catalog_alias_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAliasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAliasesRequest) ProtoMessage() {}

func (x *ListAliasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAliasesRequest.ProtoReflect.Descriptor instead.
func (*ListAliasesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{6}
}

func (x *ListAliasesRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *ListAliasesRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *ListAliasesRequest) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ListAliasesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Aliases []string         `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
}

func (x *ListAliasesResponse) Reset() {
	*x = ListAliasesResponse{}
	mi := &file_catalog_alias_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAliasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAliasesResponse) ProtoMessage() {}

func (x *ListAliasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAliasesResponse.ProtoReflect.Descriptor instead.
func (*ListAliasesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{7}
}

func (x *ListAliasesResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListAliasesResponse) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type IsAliasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *IsAliasRequest) Reset() {
	*x = IsAliasRequest{}
	mi := &file_catalog_alias_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliasRequest) ProtoMessage() {}

func (x *IsAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliasRequest.ProtoReflect.Descriptor instead.
func (*IsAliasRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{8}
}

func (x *IsAliasRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *IsAliasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IsAliasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsAlias bool             `protobuf:"varint,2,opt,name=is_alias,json=isAlias,proto3" json:"is_alias,omitempty"`
}

func (x *IsAliasResponse) Reset() {
	*x = IsAliasResponse{}
	mi := &file_catalog_alias_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliasResponse) ProtoMessage() {}

func (x *IsAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliasResponse.ProtoReflect.Descriptor instead.
func (*IsAliasResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{9}
}

func (x *IsAliasResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *IsAliasResponse) GetIsAlias() bool {
	if x != nil {
		return x.IsAlias
	}
	return false
}

type ListAliasesByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollId int64 `protobuf:"varint,1,opt,name=coll_id,json=collId,proto3" json:"coll_id,omitempty"`
}

func (x *ListAliasesByIDRequest) Reset() {
	*x = ListAliasesByIDRequest{}
	mi := &file_catalog_alias_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAliasesByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAliasesByIDRequest) ProtoMessage() {}

func (x *ListAliasesByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAliasesByIDRequest.ProtoReflect.Descriptor instead.
func (*ListAliasesByIDRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{10}
}

func (x *ListAliasesByIDRequest) GetCollId() int64 {
	if x != nil {
		return x.CollId
	}
	return 0
}

type ListAliasesByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Aliases []string         `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
}

func (x *ListAliasesByIDResponse) Reset() {
	*x = ListAliasesByIDResponse{}
	mi := &file_catalog_alias_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAliasesByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAliasesByIDResponse) ProtoMessage() {}

func (x *ListAliasesByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAliasesByIDResponse.ProtoReflect.Descriptor instead.
func (*ListAliasesByIDResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{11}
}

func (x *ListAliasesByIDResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListAliasesByIDResponse) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type CheckIfAliasCreatableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName         string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Alias          string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	CollectionName string `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
}

func (x *CheckIfAliasCreatableRequest) Reset() {
	*x = CheckIfAliasCreatableRequest{}
	mi := &file_catalog_alias_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAliasCreatableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAliasCreatableRequest) ProtoMessage() {}

func (x *CheckIfAliasCreatableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAliasCreatableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfAliasCreatableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{12}
}

func (x *CheckIfAliasCreatableRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *CheckIfAliasCreatableRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *CheckIfAliasCreatableRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type CheckIfAliasCreatableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfAliasCreatableResponse) Reset() {
	*x = CheckIfAliasCreatableResponse{}
	mi := &file_catalog_alias_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAliasCreatableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAliasCreatableResponse) ProtoMessage() {}

func (x *CheckIfAliasCreatableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAliasCreatableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfAliasCreatableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{13}
}

func (x *CheckIfAliasCreatableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckIfAliasAlterableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName         string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Alias          string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	CollectionName string `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
}

func (x *CheckIfAliasAlterableRequest) Reset() {
	*x = CheckIfAliasAlterableRequest{}
	mi := &file_catalog_alias_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAliasAlterableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAliasAlterableRequest) ProtoMessage() {}

func (x *CheckIfAliasAlterableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAliasAlterableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfAliasAlterableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{14}
}

func (x *CheckIfAliasAlterableRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *CheckIfAliasAlterableRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *CheckIfAliasAlterableRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type CheckIfAliasAlterableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfAliasAlterableResponse) Reset() {
	*x = CheckIfAliasAlterableResponse{}
	mi := &file_catalog_alias_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAliasAlterableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAliasAlterableResponse) ProtoMessage() {}

func (x *CheckIfAliasAlterableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAliasAlterableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfAliasAlterableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{15}
}

func (x *CheckIfAliasAlterableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckIfAliasDroppableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Alias  string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *CheckIfAliasDroppableRequest) Reset() {
	*x = CheckIfAliasDroppableRequest{}
	mi := &file_catalog_alias_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAliasDroppableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAliasDroppableRequest) ProtoMessage() {}

func (x *CheckIfAliasDroppableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAliasDroppableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfAliasDroppableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{16}
}

func (x *CheckIfAliasDroppableRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *CheckIfAliasDroppableRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CheckIfAliasDroppableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfAliasDroppableResponse) Reset() {
	*x = CheckIfAliasDroppableResponse{}
	mi := &file_catalog_alias_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAliasDroppableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAliasDroppableResponse) ProtoMessage() {}

func (x *CheckIfAliasDroppableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_alias_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAliasDroppableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfAliasDroppableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_alias_proto_rawDescGZIP(), []int{17}
}

func (x *CheckIfAliasDroppableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_catalog_alias_proto protoreflect.FileDescriptor

var file_catalog_alias_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78, 0x0a, 0x11, 0x41, 0x6c, 0x74,
	0x65, 0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x46,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74,
	0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x22, 0x49, 0x0a, 0x12, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x76,
	0x0a, 0x10, 0x44, 0x72, 0x6f, 0x70, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x45, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x22, 0x48, 0x0a, 0x11, 0x44, 0x72, 0x6f, 0x70, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x55, 0x0a, 0x14, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x74, 0x73, 0x22, 0x75, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x66,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x74, 0x73, 0x22, 0x64, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0e,
	0x49, 0x73, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x0f, 0x49,
	0x73, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x31,
	0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6c, 0x49,
	0x64, 0x22, 0x68, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x22, 0x76, 0x0a, 0x1c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64,
	0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x76, 0x0a, 0x1c, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x66, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x54, 0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4d, 0x0a, 0x1c, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x66, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x54, 0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49,
	0x66, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_alias_proto_rawDescOnce sync.Once
	file_catalog_alias_proto_rawDescData = file_catalog_alias_proto_rawDesc
)

func file_catalog_alias_proto_rawDescGZIP() []byte {
	file_catalog_alias_proto_rawDescOnce.Do(func() {
		file_catalog_alias_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_alias_proto_rawDescData)
	})
	return file_catalog_alias_proto_rawDescData
}

var file_catalog_alias_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_catalog_alias_proto_goTypes = []any{
	(*AlterAliasRequest)(nil),                  // 0: milvus.proto.catalog.AlterAliasRequest
	(*AlterAliasResponse)(nil),                 // 1: milvus.proto.catalog.AlterAliasResponse
	(*DropAliasRequest)(nil),                   // 2: milvus.proto.catalog.DropAliasRequest
	(*DropAliasResponse)(nil),                  // 3: milvus.proto.catalog.DropAliasResponse
	(*DescribeAliasRequest)(nil),               // 4: milvus.proto.catalog.DescribeAliasRequest
	(*DescribeAliasResponse)(nil),              // 5: milvus.proto.catalog.DescribeAliasResponse
	(*ListAliasesRequest)(nil),                 // 6: milvus.proto.catalog.ListAliasesRequest
	(*ListAliasesResponse)(nil),                // 7: milvus.proto.catalog.ListAliasesResponse
	(*IsAliasRequest)(nil),                     // 8: milvus.proto.catalog.IsAliasRequest
	(*IsAliasResponse)(nil),                    // 9: milvus.proto.catalog.IsAliasResponse
	(*ListAliasesByIDRequest)(nil),             // 10: milvus.proto.catalog.ListAliasesByIDRequest
	(*ListAliasesByIDResponse)(nil),            // 11: milvus.proto.catalog.ListAliasesByIDResponse
	(*CheckIfAliasCreatableRequest)(nil),       // 12: milvus.proto.catalog.CheckIfAliasCreatableRequest
	(*CheckIfAliasCreatableResponse)(nil),      // 13: milvus.proto.catalog.CheckIfAliasCreatableResponse
	(*CheckIfAliasAlterableRequest)(nil),       // 14: milvus.proto.catalog.CheckIfAliasAlterableRequest
	(*CheckIfAliasAlterableResponse)(nil),      // 15: milvus.proto.catalog.CheckIfAliasAlterableResponse
	(*CheckIfAliasDroppableRequest)(nil),       // 16: milvus.proto.catalog.CheckIfAliasDroppableRequest
	(*CheckIfAliasDroppableResponse)(nil),      // 17: milvus.proto.catalog.CheckIfAliasDroppableResponse
	(*messagespb.AlterAliasMessageHeader)(nil), // 18: milvus.proto.messages.AlterAliasMessageHeader
	(*commonpb.Status)(nil),                    // 19: milvus.proto.common.Status
	(*messagespb.DropAliasMessageHeader)(nil),  // 20: milvus.proto.messages.DropAliasMessageHeader
}
var file_catalog_alias_proto_depIdxs = []int32{
	18, // 0: milvus.proto.catalog.AlterAliasRequest.header:type_name -> milvus.proto.messages.AlterAliasMessageHeader
	19, // 1: milvus.proto.catalog.AlterAliasResponse.status:type_name -> milvus.proto.common.Status
	20, // 2: milvus.proto.catalog.DropAliasRequest.header:type_name -> milvus.proto.messages.DropAliasMessageHeader
	19, // 3: milvus.proto.catalog.DropAliasResponse.status:type_name -> milvus.proto.common.Status
	19, // 4: milvus.proto.catalog.DescribeAliasResponse.status:type_name -> milvus.proto.common.Status
	19, // 5: milvus.proto.catalog.ListAliasesResponse.status:type_name -> milvus.proto.common.Status
	19, // 6: milvus.proto.catalog.IsAliasResponse.status:type_name -> milvus.proto.common.Status
	19, // 7: milvus.proto.catalog.ListAliasesByIDResponse.status:type_name -> milvus.proto.common.Status
	19, // 8: milvus.proto.catalog.CheckIfAliasCreatableResponse.status:type_name -> milvus.proto.common.Status
	19, // 9: milvus.proto.catalog.CheckIfAliasAlterableResponse.status:type_name -> milvus.proto.common.Status
	19, // 10: milvus.proto.catalog.CheckIfAliasDroppableResponse.status:type_name -> milvus.proto.common.Status
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_catalog_alias_proto_init() }
func file_catalog_alias_proto_init() {
	if File_catalog_alias_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_alias_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_alias_proto_goTypes,
		DependencyIndexes: file_catalog_alias_proto_depIdxs,
		MessageInfos:      file_catalog_alias_proto_msgTypes,
	}.Build()
	File_catalog_alias_proto = out.File
	file_catalog_alias_proto_rawDesc = nil
	file_catalog_alias_proto_goTypes = nil
	file_catalog_alias_proto_depIdxs = nil
}
