// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_dbchecks.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	milvuspb "github.com/milvus-io/milvus-proto/go-api/v3/milvuspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckIfDatabaseCreatableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.CreateDatabaseRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfDatabaseCreatableRequest) Reset() {
	*x = CheckIfDatabaseCreatableRequest{}
	mi := &file_catalog_dbchecks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDatabaseCreatableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDatabaseCreatableRequest) ProtoMessage() {}

func (x *CheckIfDatabaseCreatableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_dbchecks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDatabaseCreatableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfDatabaseCreatableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_dbchecks_proto_rawDescGZIP(), []int{0}
}

func (x *CheckIfDatabaseCreatableRequest) GetReq() *milvuspb.CreateDatabaseRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfDatabaseCreatableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfDatabaseCreatableResponse) Reset() {
	*x = CheckIfDatabaseCreatableResponse{}
	mi := &file_catalog_dbchecks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDatabaseCreatableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDatabaseCreatableResponse) ProtoMessage() {}

func (x *CheckIfDatabaseCreatableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_dbchecks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDatabaseCreatableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfDatabaseCreatableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_dbchecks_proto_rawDescGZIP(), []int{1}
}

func (x *CheckIfDatabaseCreatableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckIfDatabaseDroppableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.DropDatabaseRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfDatabaseDroppableRequest) Reset() {
	*x = CheckIfDatabaseDroppableRequest{}
	mi := &file_catalog_dbchecks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDatabaseDroppableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDatabaseDroppableRequest) ProtoMessage() {}

func (x *CheckIfDatabaseDroppableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_dbchecks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDatabaseDroppableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfDatabaseDroppableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_dbchecks_proto_rawDescGZIP(), []int{2}
}

func (x *CheckIfDatabaseDroppableRequest) GetReq() *milvuspb.DropDatabaseRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfDatabaseDroppableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfDatabaseDroppableResponse) Reset() {
	*x = CheckIfDatabaseDroppableResponse{}
	mi := &file_catalog_dbchecks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDatabaseDroppableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDatabaseDroppableResponse) ProtoMessage() {}

func (x *CheckIfDatabaseDroppableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_dbchecks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDatabaseDroppableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfDatabaseDroppableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_dbchecks_proto_rawDescGZIP(), []int{3}
}

func (x *CheckIfDatabaseDroppableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_catalog_dbchecks_proto protoreflect.FileDescriptor

var file_catalog_dbchecks_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x64, 0x62, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x1f, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x66, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x57, 0x0a, 0x20, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x5d, 0x0a, 0x1f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03,
	0x72, 0x65, 0x71, 0x22, 0x57, 0x0a, 0x20, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_dbchecks_proto_rawDescOnce sync.Once
	file_catalog_dbchecks_proto_rawDescData = file_catalog_dbchecks_proto_rawDesc
)

func file_catalog_dbchecks_proto_rawDescGZIP() []byte {
	file_catalog_dbchecks_proto_rawDescOnce.Do(func() {
		file_catalog_dbchecks_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_dbchecks_proto_rawDescData)
	})
	return file_catalog_dbchecks_proto_rawDescData
}

var file_catalog_dbchecks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_catalog_dbchecks_proto_goTypes = []any{
	(*CheckIfDatabaseCreatableRequest)(nil),  // 0: milvus.proto.catalog.CheckIfDatabaseCreatableRequest
	(*CheckIfDatabaseCreatableResponse)(nil), // 1: milvus.proto.catalog.CheckIfDatabaseCreatableResponse
	(*CheckIfDatabaseDroppableRequest)(nil),  // 2: milvus.proto.catalog.CheckIfDatabaseDroppableRequest
	(*CheckIfDatabaseDroppableResponse)(nil), // 3: milvus.proto.catalog.CheckIfDatabaseDroppableResponse
	(*milvuspb.CreateDatabaseRequest)(nil),   // 4: milvus.proto.milvus.CreateDatabaseRequest
	(*commonpb.Status)(nil),                  // 5: milvus.proto.common.Status
	(*milvuspb.DropDatabaseRequest)(nil),     // 6: milvus.proto.milvus.DropDatabaseRequest
}
var file_catalog_dbchecks_proto_depIdxs = []int32{
	4, // 0: milvus.proto.catalog.CheckIfDatabaseCreatableRequest.req:type_name -> milvus.proto.milvus.CreateDatabaseRequest
	5, // 1: milvus.proto.catalog.CheckIfDatabaseCreatableResponse.status:type_name -> milvus.proto.common.Status
	6, // 2: milvus.proto.catalog.CheckIfDatabaseDroppableRequest.req:type_name -> milvus.proto.milvus.DropDatabaseRequest
	5, // 3: milvus.proto.catalog.CheckIfDatabaseDroppableResponse.status:type_name -> milvus.proto.common.Status
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_dbchecks_proto_init() }
func file_catalog_dbchecks_proto_init() {
	if File_catalog_dbchecks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_dbchecks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_dbchecks_proto_goTypes,
		DependencyIndexes: file_catalog_dbchecks_proto_depIdxs,
		MessageInfos:      file_catalog_dbchecks_proto_msgTypes,
	}.Build()
	File_catalog_dbchecks_proto = out.File
	file_catalog_dbchecks_proto_rawDesc = nil
	file_catalog_dbchecks_proto_goTypes = nil
	file_catalog_dbchecks_proto_depIdxs = nil
}
