// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_fileresource.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	internalpb "github.com/milvus-io/milvus/pkg/v3/proto/internalpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileResourceInt64List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *FileResourceInt64List) Reset() {
	*x = FileResourceInt64List{}
	mi := &file_catalog_fileresource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResourceInt64List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResourceInt64List) ProtoMessage() {}

func (x *FileResourceInt64List) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResourceInt64List.ProtoReflect.Descriptor instead.
func (*FileResourceInt64List) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{0}
}

func (x *FileResourceInt64List) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AddFileResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *internalpb.FileResourceInfo `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *AddFileResourceRequest) Reset() {
	*x = AddFileResourceRequest{}
	mi := &file_catalog_fileresource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFileResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileResourceRequest) ProtoMessage() {}

func (x *AddFileResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileResourceRequest.ProtoReflect.Descriptor instead.
func (*AddFileResourceRequest) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{1}
}

func (x *AddFileResourceRequest) GetResource() *internalpb.FileResourceInfo {
	if x != nil {
		return x.Resource
	}
	return nil
}

type AddFileResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddFileResourceResponse) Reset() {
	*x = AddFileResourceResponse{}
	mi := &file_catalog_fileresource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFileResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileResourceResponse) ProtoMessage() {}

func (x *AddFileResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileResourceResponse.ProtoReflect.Descriptor instead.
func (*AddFileResourceResponse) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{2}
}

func (x *AddFileResourceResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type RemoveFileResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RemoveFileResourceRequest) Reset() {
	*x = RemoveFileResourceRequest{}
	mi := &file_catalog_fileresource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResourceRequest) ProtoMessage() {}

func (x *RemoveFileResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResourceRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileResourceRequest) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFileResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveFileResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Removed bool             `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *RemoveFileResourceResponse) Reset() {
	*x = RemoveFileResourceResponse{}
	mi := &file_catalog_fileresource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResourceResponse) ProtoMessage() {}

func (x *RemoveFileResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResourceResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileResourceResponse) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFileResourceResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RemoveFileResourceResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListFileResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFileResourceRequest) Reset() {
	*x = ListFileResourceRequest{}
	mi := &file_catalog_fileresource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileResourceRequest) ProtoMessage() {}

func (x *ListFileResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileResourceRequest.ProtoReflect.Descriptor instead.
func (*ListFileResourceRequest) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{5}
}

type ListFileResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *commonpb.Status               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Resources []*internalpb.FileResourceInfo `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Version   uint64                         `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ListFileResourceResponse) Reset() {
	*x = ListFileResourceResponse{}
	mi := &file_catalog_fileresource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileResourceResponse) ProtoMessage() {}

func (x *ListFileResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileResourceResponse.ProtoReflect.Descriptor instead.
func (*ListFileResourceResponse) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{6}
}

func (x *ListFileResourceResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListFileResourceResponse) GetResources() []*internalpb.FileResourceInfo {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListFileResourceResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type IncFileResourceRefCntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *IncFileResourceRefCntRequest) Reset() {
	*x = IncFileResourceRefCntRequest{}
	mi := &file_catalog_fileresource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncFileResourceRefCntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncFileResourceRefCntRequest) ProtoMessage() {}

func (x *IncFileResourceRefCntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncFileResourceRefCntRequest.ProtoReflect.Descriptor instead.
func (*IncFileResourceRefCntRequest) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{7}
}

func (x *IncFileResourceRefCntRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type IncFileResourceRefCntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *IncFileResourceRefCntResponse) Reset() {
	*x = IncFileResourceRefCntResponse{}
	mi := &file_catalog_fileresource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncFileResourceRefCntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncFileResourceRefCntResponse) ProtoMessage() {}

func (x *IncFileResourceRefCntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncFileResourceRefCntResponse.ProtoReflect.Descriptor instead.
func (*IncFileResourceRefCntResponse) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{8}
}

func (x *IncFileResourceRefCntResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DecFileResourceRefCntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DecFileResourceRefCntRequest) Reset() {
	*x = DecFileResourceRefCntRequest{}
	mi := &file_catalog_fileresource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecFileResourceRefCntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecFileResourceRefCntRequest) ProtoMessage() {}

func (x *DecFileResourceRefCntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecFileResourceRefCntRequest.ProtoReflect.Descriptor instead.
func (*DecFileResourceRefCntRequest) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{9}
}

func (x *DecFileResourceRefCntRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DecFileResourceRefCntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DecFileResourceRefCntResponse) Reset() {
	*x = DecFileResourceRefCntResponse{}
	mi := &file_catalog_fileresource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecFileResourceRefCntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecFileResourceRefCntResponse) ProtoMessage() {}

func (x *DecFileResourceRefCntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecFileResourceRefCntResponse.ProtoReflect.Descriptor instead.
func (*DecFileResourceRefCntResponse) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{10}
}

func (x *DecFileResourceRefCntResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type RecoverFileResourceRefCntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingCollections map[int64]*FileResourceInt64List `protobuf:"bytes,1,rep,name=pending_collections,json=pendingCollections,proto3" json:"pending_collections,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RecoverFileResourceRefCntRequest) Reset() {
	*x = RecoverFileResourceRefCntRequest{}
	mi := &file_catalog_fileresource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverFileResourceRefCntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverFileResourceRefCntRequest) ProtoMessage() {}

func (x *RecoverFileResourceRefCntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverFileResourceRefCntRequest.ProtoReflect.Descriptor instead.
func (*RecoverFileResourceRefCntRequest) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{11}
}

func (x *RecoverFileResourceRefCntRequest) GetPendingCollections() map[int64]*FileResourceInt64List {
	if x != nil {
		return x.PendingCollections
	}
	return nil
}

type RecoverFileResourceRefCntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RecoverFileResourceRefCntResponse) Reset() {
	*x = RecoverFileResourceRefCntResponse{}
	mi := &file_catalog_fileresource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverFileResourceRefCntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverFileResourceRefCntResponse) ProtoMessage() {}

func (x *RecoverFileResourceRefCntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_fileresource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverFileResourceRefCntResponse.ProtoReflect.Descriptor instead.
func (*RecoverFileResourceRefCntResponse) Descriptor() ([]byte, []int) {
	return file_catalog_fileresource_proto_rawDescGZIP(), []int{12}
}

func (x *RecoverFileResourceRefCntResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_catalog_fileresource_proto protoreflect.FileDescriptor

var file_catalog_fileresource_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x29, 0x0a, 0x15, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x6e, 0x74, 0x36, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x5d, 0x0a, 0x16, 0x41,
	0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x4e, 0x0a, 0x17, 0x41, 0x64,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x19, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6b, 0x0a, 0x1a, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x45, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x1c, 0x49, 0x6e, 0x63, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x66, 0x43, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x54, 0x0a, 0x1d, 0x49, 0x6e, 0x63, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x66, 0x43, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x30,
	0x0a, 0x1c, 0x44, 0x65, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x66, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x22, 0x54, 0x0a, 0x1d, 0x44, 0x65, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x66, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x97, 0x02, 0x0a, 0x20, 0x52, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x66, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x7f, 0x0a, 0x13, 0x70,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4e, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x66, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x12, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x72, 0x0a, 0x17,
	0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x41, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x36,
	0x34, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x58, 0x0a, 0x21, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x66, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2d,
	0x69, 0x6f, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x33,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_fileresource_proto_rawDescOnce sync.Once
	file_catalog_fileresource_proto_rawDescData = file_catalog_fileresource_proto_rawDesc
)

func file_catalog_fileresource_proto_rawDescGZIP() []byte {
	file_catalog_fileresource_proto_rawDescOnce.Do(func() {
		file_catalog_fileresource_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_fileresource_proto_rawDescData)
	})
	return file_catalog_fileresource_proto_rawDescData
}

var file_catalog_fileresource_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_catalog_fileresource_proto_goTypes = []any{
	(*FileResourceInt64List)(nil),             // 0: milvus.proto.catalog.FileResourceInt64List
	(*AddFileResourceRequest)(nil),            // 1: milvus.proto.catalog.AddFileResourceRequest
	(*AddFileResourceResponse)(nil),           // 2: milvus.proto.catalog.AddFileResourceResponse
	(*RemoveFileResourceRequest)(nil),         // 3: milvus.proto.catalog.RemoveFileResourceRequest
	(*RemoveFileResourceResponse)(nil),        // 4: milvus.proto.catalog.RemoveFileResourceResponse
	(*ListFileResourceRequest)(nil),           // 5: milvus.proto.catalog.ListFileResourceRequest
	(*ListFileResourceResponse)(nil),          // 6: milvus.proto.catalog.ListFileResourceResponse
	(*IncFileResourceRefCntRequest)(nil),      // 7: milvus.proto.catalog.IncFileResourceRefCntRequest
	(*IncFileResourceRefCntResponse)(nil),     // 8: milvus.proto.catalog.IncFileResourceRefCntResponse
	(*DecFileResourceRefCntRequest)(nil),      // 9: milvus.proto.catalog.DecFileResourceRefCntRequest
	(*DecFileResourceRefCntResponse)(nil),     // 10: milvus.proto.catalog.DecFileResourceRefCntResponse
	(*RecoverFileResourceRefCntRequest)(nil),  // 11: milvus.proto.catalog.RecoverFileResourceRefCntRequest
	(*RecoverFileResourceRefCntResponse)(nil), // 12: milvus.proto.catalog.RecoverFileResourceRefCntResponse
	nil,                                 // 13: milvus.proto.catalog.RecoverFileResourceRefCntRequest.PendingCollectionsEntry
	(*internalpb.FileResourceInfo)(nil), // 14: milvus.proto.internal.FileResourceInfo
	(*commonpb.Status)(nil),             // 15: milvus.proto.common.Status
}
var file_catalog_fileresource_proto_depIdxs = []int32{
	14, // 0: milvus.proto.catalog.AddFileResourceRequest.resource:type_name -> milvus.proto.internal.FileResourceInfo
	15, // 1: milvus.proto.catalog.AddFileResourceResponse.status:type_name -> milvus.proto.common.Status
	15, // 2: milvus.proto.catalog.RemoveFileResourceResponse.status:type_name -> milvus.proto.common.Status
	15, // 3: milvus.proto.catalog.ListFileResourceResponse.status:type_name -> milvus.proto.common.Status
	14, // 4: milvus.proto.catalog.ListFileResourceResponse.resources:type_name -> milvus.proto.internal.FileResourceInfo
	15, // 5: milvus.proto.catalog.IncFileResourceRefCntResponse.status:type_name -> milvus.proto.common.Status
	15, // 6: milvus.proto.catalog.DecFileResourceRefCntResponse.status:type_name -> milvus.proto.common.Status
	13, // 7: milvus.proto.catalog.RecoverFileResourceRefCntRequest.pending_collections:type_name -> milvus.proto.catalog.RecoverFileResourceRefCntRequest.PendingCollectionsEntry
	15, // 8: milvus.proto.catalog.RecoverFileResourceRefCntResponse.status:type_name -> milvus.proto.common.Status
	0,  // 9: milvus.proto.catalog.RecoverFileResourceRefCntRequest.PendingCollectionsEntry.value:type_name -> milvus.proto.catalog.FileResourceInt64List
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_catalog_fileresource_proto_init() }
func file_catalog_fileresource_proto_init() {
	if File_catalog_fileresource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_fileresource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_fileresource_proto_goTypes,
		DependencyIndexes: file_catalog_fileresource_proto_depIdxs,
		MessageInfos:      file_catalog_fileresource_proto_msgTypes,
	}.Build()
	File_catalog_fileresource_proto = out.File
	file_catalog_fileresource_proto_rawDesc = nil
	file_catalog_fileresource_proto_goTypes = nil
	file_catalog_fileresource_proto_depIdxs = nil
}
