// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_credential.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	milvuspb "github.com/milvus-io/milvus-proto/go-api/v3/milvuspb"
	internalpb "github.com/milvus-io/milvus/pkg/v3/proto/internalpb"
	messagespb "github.com/milvus-io/milvus/pkg/v3/proto/messagespb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitCredentialRequest) Reset() {
	*x = InitCredentialRequest{}
	mi := &file_catalog_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCredentialRequest) ProtoMessage() {}

func (x *InitCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCredentialRequest.ProtoReflect.Descriptor instead.
func (*InitCredentialRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{0}
}

type InitCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InitCredentialResponse) Reset() {
	*x = InitCredentialResponse{}
	mi := &file_catalog_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCredentialResponse) ProtoMessage() {}

func (x *InitCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCredentialResponse.ProtoReflect.Descriptor instead.
func (*InitCredentialResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{1}
}

func (x *InitCredentialResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// AlterCredential [B]: rebuilt from AlterUserMessageV2 broadcast result.
type AlterCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *messagespb.AlterUserMessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body     *messagespb.AlterUserMessageBody   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	TimeTick uint64                             `protobuf:"varint,3,opt,name=time_tick,json=timeTick,proto3" json:"time_tick,omitempty"`
}

func (x *AlterCredentialRequest) Reset() {
	*x = AlterCredentialRequest{}
	mi := &file_catalog_credential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterCredentialRequest) ProtoMessage() {}

func (x *AlterCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterCredentialRequest.ProtoReflect.Descriptor instead.
func (*AlterCredentialRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{2}
}

func (x *AlterCredentialRequest) GetHeader() *messagespb.AlterUserMessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AlterCredentialRequest) GetBody() *messagespb.AlterUserMessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AlterCredentialRequest) GetTimeTick() uint64 {
	if x != nil {
		return x.TimeTick
	}
	return 0
}

type AlterCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AlterCredentialResponse) Reset() {
	*x = AlterCredentialResponse{}
	mi := &file_catalog_credential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterCredentialResponse) ProtoMessage() {}

func (x *AlterCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterCredentialResponse.ProtoReflect.Descriptor instead.
func (*AlterCredentialResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{3}
}

func (x *AlterCredentialResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// DeleteCredential [B]: rebuilt from DropUserMessageV2 broadcast result.
type DeleteCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *messagespb.DropUserMessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TimeTick uint64                            `protobuf:"varint,2,opt,name=time_tick,json=timeTick,proto3" json:"time_tick,omitempty"`
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_catalog_credential_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCredentialRequest) GetHeader() *messagespb.DropUserMessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteCredentialRequest) GetTimeTick() uint64 {
	if x != nil {
		return x.TimeTick
	}
	return 0
}

type DeleteCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_catalog_credential_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCredentialResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_catalog_credential_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{6}
}

func (x *GetCredentialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     *commonpb.Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Credential *internalpb.CredentialInfo `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_catalog_credential_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{7}
}

func (x *GetCredentialResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetCredentialResponse) GetCredential() *internalpb.CredentialInfo {
	if x != nil {
		return x.Credential
	}
	return nil
}

type ListCredentialUsernamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCredentialUsernamesRequest) Reset() {
	*x = ListCredentialUsernamesRequest{}
	mi := &file_catalog_credential_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialUsernamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialUsernamesRequest) ProtoMessage() {}

func (x *ListCredentialUsernamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialUsernamesRequest.ProtoReflect.Descriptor instead.
func (*ListCredentialUsernamesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{8}
}

type ListCredentialUsernamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Usernames []string         `protobuf:"bytes,2,rep,name=usernames,proto3" json:"usernames,omitempty"`
}

func (x *ListCredentialUsernamesResponse) Reset() {
	*x = ListCredentialUsernamesResponse{}
	mi := &file_catalog_credential_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialUsernamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialUsernamesResponse) ProtoMessage() {}

func (x *ListCredentialUsernamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialUsernamesResponse.ProtoReflect.Descriptor instead.
func (*ListCredentialUsernamesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{9}
}

func (x *ListCredentialUsernamesResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListCredentialUsernamesResponse) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type CheckIfAddCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredInfo *internalpb.CredentialInfo `protobuf:"bytes,1,opt,name=cred_info,json=credInfo,proto3" json:"cred_info,omitempty"`
}

func (x *CheckIfAddCredentialRequest) Reset() {
	*x = CheckIfAddCredentialRequest{}
	mi := &file_catalog_credential_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAddCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAddCredentialRequest) ProtoMessage() {}

func (x *CheckIfAddCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAddCredentialRequest.ProtoReflect.Descriptor instead.
func (*CheckIfAddCredentialRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{10}
}

func (x *CheckIfAddCredentialRequest) GetCredInfo() *internalpb.CredentialInfo {
	if x != nil {
		return x.CredInfo
	}
	return nil
}

type CheckIfAddCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfAddCredentialResponse) Reset() {
	*x = CheckIfAddCredentialResponse{}
	mi := &file_catalog_credential_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAddCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAddCredentialResponse) ProtoMessage() {}

func (x *CheckIfAddCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAddCredentialResponse.ProtoReflect.Descriptor instead.
func (*CheckIfAddCredentialResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{11}
}

func (x *CheckIfAddCredentialResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckIfUpdateCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredInfo *internalpb.CredentialInfo `protobuf:"bytes,1,opt,name=cred_info,json=credInfo,proto3" json:"cred_info,omitempty"`
}

func (x *CheckIfUpdateCredentialRequest) Reset() {
	*x = CheckIfUpdateCredentialRequest{}
	mi := &file_catalog_credential_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfUpdateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfUpdateCredentialRequest) ProtoMessage() {}

func (x *CheckIfUpdateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfUpdateCredentialRequest.ProtoReflect.Descriptor instead.
func (*CheckIfUpdateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{12}
}

func (x *CheckIfUpdateCredentialRequest) GetCredInfo() *internalpb.CredentialInfo {
	if x != nil {
		return x.CredInfo
	}
	return nil
}

type CheckIfUpdateCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfUpdateCredentialResponse) Reset() {
	*x = CheckIfUpdateCredentialResponse{}
	mi := &file_catalog_credential_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfUpdateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfUpdateCredentialResponse) ProtoMessage() {}

func (x *CheckIfUpdateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfUpdateCredentialResponse.ProtoReflect.Descriptor instead.
func (*CheckIfUpdateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{13}
}

func (x *CheckIfUpdateCredentialResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckIfDeleteCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.DeleteCredentialRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfDeleteCredentialRequest) Reset() {
	*x = CheckIfDeleteCredentialRequest{}
	mi := &file_catalog_credential_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDeleteCredentialRequest) ProtoMessage() {}

func (x *CheckIfDeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*CheckIfDeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{14}
}

func (x *CheckIfDeleteCredentialRequest) GetReq() *milvuspb.DeleteCredentialRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfDeleteCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfDeleteCredentialResponse) Reset() {
	*x = CheckIfDeleteCredentialResponse{}
	mi := &file_catalog_credential_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDeleteCredentialResponse) ProtoMessage() {}

func (x *CheckIfDeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_credential_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*CheckIfDeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_catalog_credential_proto_rawDescGZIP(), []int{15}
}

func (x *CheckIfDeleteCredentialResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_catalog_credential_proto protoreflect.FileDescriptor

var file_catalog_credential_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x69, 0x6c, 0x76,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15,
	0x49, 0x6e, 0x69, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x16, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x45, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x6c, 0x74,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x64,
	0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x74, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x54, 0x69, 0x63, 0x6b, 0x22, 0x4e, 0x0a, 0x17, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x7c, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x44, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2c, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x69,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x69,
	0x63, 0x6b, 0x22, 0x4f, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x45, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x20, 0x0a,
	0x1e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x74, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x1b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66,
	0x41, 0x64, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x63, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x53, 0x0a, 0x1c, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x49, 0x66, 0x41, 0x64, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x64, 0x0a,
	0x1e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x42, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x72, 0x65, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x56, 0x0a, 0x1f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x60, 0x0a, 0x1e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x56, 0x0a,
	0x1f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_catalog_credential_proto_rawDescOnce sync.Once
	file_catalog_credential_proto_rawDescData = file_catalog_credential_proto_rawDesc
)

func file_catalog_credential_proto_rawDescGZIP() []byte {
	file_catalog_credential_proto_rawDescOnce.Do(func() {
		file_catalog_credential_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_credential_proto_rawDescData)
	})
	return file_catalog_credential_proto_rawDescData
}

var file_catalog_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_catalog_credential_proto_goTypes = []any{
	(*InitCredentialRequest)(nil),             // 0: milvus.proto.catalog.InitCredentialRequest
	(*InitCredentialResponse)(nil),            // 1: milvus.proto.catalog.InitCredentialResponse
	(*AlterCredentialRequest)(nil),            // 2: milvus.proto.catalog.AlterCredentialRequest
	(*AlterCredentialResponse)(nil),           // 3: milvus.proto.catalog.AlterCredentialResponse
	(*DeleteCredentialRequest)(nil),           // 4: milvus.proto.catalog.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil),          // 5: milvus.proto.catalog.DeleteCredentialResponse
	(*GetCredentialRequest)(nil),              // 6: milvus.proto.catalog.GetCredentialRequest
	(*GetCredentialResponse)(nil),             // 7: milvus.proto.catalog.GetCredentialResponse
	(*ListCredentialUsernamesRequest)(nil),    // 8: milvus.proto.catalog.ListCredentialUsernamesRequest
	(*ListCredentialUsernamesResponse)(nil),   // 9: milvus.proto.catalog.ListCredentialUsernamesResponse
	(*CheckIfAddCredentialRequest)(nil),       // 10: milvus.proto.catalog.CheckIfAddCredentialRequest
	(*CheckIfAddCredentialResponse)(nil),      // 11: milvus.proto.catalog.CheckIfAddCredentialResponse
	(*CheckIfUpdateCredentialRequest)(nil),    // 12: milvus.proto.catalog.CheckIfUpdateCredentialRequest
	(*CheckIfUpdateCredentialResponse)(nil),   // 13: milvus.proto.catalog.CheckIfUpdateCredentialResponse
	(*CheckIfDeleteCredentialRequest)(nil),    // 14: milvus.proto.catalog.CheckIfDeleteCredentialRequest
	(*CheckIfDeleteCredentialResponse)(nil),   // 15: milvus.proto.catalog.CheckIfDeleteCredentialResponse
	(*commonpb.Status)(nil),                   // 16: milvus.proto.common.Status
	(*messagespb.AlterUserMessageHeader)(nil), // 17: milvus.proto.messages.AlterUserMessageHeader
	(*messagespb.AlterUserMessageBody)(nil),   // 18: milvus.proto.messages.AlterUserMessageBody
	(*messagespb.DropUserMessageHeader)(nil),  // 19: milvus.proto.messages.DropUserMessageHeader
	(*internalpb.CredentialInfo)(nil),         // 20: milvus.proto.internal.CredentialInfo
	(*milvuspb.DeleteCredentialRequest)(nil),  // 21: milvus.proto.milvus.DeleteCredentialRequest
}
var file_catalog_credential_proto_depIdxs = []int32{
	16, // 0: milvus.proto.catalog.InitCredentialResponse.status:type_name -> milvus.proto.common.Status
	17, // 1: milvus.proto.catalog.AlterCredentialRequest.header:type_name -> milvus.proto.messages.AlterUserMessageHeader
	18, // 2: milvus.proto.catalog.AlterCredentialRequest.body:type_name -> milvus.proto.messages.AlterUserMessageBody
	16, // 3: milvus.proto.catalog.AlterCredentialResponse.status:type_name -> milvus.proto.common.Status
	19, // 4: milvus.proto.catalog.DeleteCredentialRequest.header:type_name -> milvus.proto.messages.DropUserMessageHeader
	16, // 5: milvus.proto.catalog.DeleteCredentialResponse.status:type_name -> milvus.proto.common.Status
	16, // 6: milvus.proto.catalog.GetCredentialResponse.status:type_name -> milvus.proto.common.Status
	20, // 7: milvus.proto.catalog.GetCredentialResponse.credential:type_name -> milvus.proto.internal.CredentialInfo
	16, // 8: milvus.proto.catalog.ListCredentialUsernamesResponse.status:type_name -> milvus.proto.common.Status
	20, // 9: milvus.proto.catalog.CheckIfAddCredentialRequest.cred_info:type_name -> milvus.proto.internal.CredentialInfo
	16, // 10: milvus.proto.catalog.CheckIfAddCredentialResponse.status:type_name -> milvus.proto.common.Status
	20, // 11: milvus.proto.catalog.CheckIfUpdateCredentialRequest.cred_info:type_name -> milvus.proto.internal.CredentialInfo
	16, // 12: milvus.proto.catalog.CheckIfUpdateCredentialResponse.status:type_name -> milvus.proto.common.Status
	21, // 13: milvus.proto.catalog.CheckIfDeleteCredentialRequest.req:type_name -> milvus.proto.milvus.DeleteCredentialRequest
	16, // 14: milvus.proto.catalog.CheckIfDeleteCredentialResponse.status:type_name -> milvus.proto.common.Status
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_catalog_credential_proto_init() }
func file_catalog_credential_proto_init() {
	if File_catalog_credential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_credential_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_credential_proto_goTypes,
		DependencyIndexes: file_catalog_credential_proto_depIdxs,
		MessageInfos:      file_catalog_credential_proto_msgTypes,
	}.Build()
	File_catalog_credential_proto = out.File
	file_catalog_credential_proto_rawDesc = nil
	file_catalog_credential_proto_goTypes = nil
	file_catalog_credential_proto_depIdxs = nil
}
