// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_role.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	milvuspb "github.com/milvus-io/milvus-proto/go-api/v3/milvuspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateRole
type CreateRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string               `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Entity *milvuspb.RoleEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CreateRoleRequest) GetEntity() *milvuspb.RoleEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// AlterRole
type AlterRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string               `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Entity *milvuspb.RoleEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *AlterRoleRequest) Reset() {
	*x = AlterRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterRoleRequest) ProtoMessage() {}

func (x *AlterRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterRoleRequest.ProtoReflect.Descriptor instead.
func (*AlterRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{2}
}

func (x *AlterRoleRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AlterRoleRequest) GetEntity() *milvuspb.RoleEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type AlterRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AlterRoleResponse) Reset() {
	*x = AlterRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterRoleResponse) ProtoMessage() {}

func (x *AlterRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterRoleResponse.ProtoReflect.Descriptor instead.
func (*AlterRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{3}
}

func (x *AlterRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// DropRole
type DropRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant   string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
}

func (x *DropRoleRequest) Reset() {
	*x = DropRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropRoleRequest) ProtoMessage() {}

func (x *DropRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropRoleRequest.ProtoReflect.Descriptor instead.
func (*DropRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{4}
}

func (x *DropRoleRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *DropRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type DropRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DropRoleResponse) Reset() {
	*x = DropRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropRoleResponse) ProtoMessage() {}

func (x *DropRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropRoleResponse.ProtoReflect.Descriptor instead.
func (*DropRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{5}
}

func (x *DropRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// OperateUserRole
type OperateUserRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant      string                       `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	UserEntity  *milvuspb.UserEntity         `protobuf:"bytes,2,opt,name=user_entity,json=userEntity,proto3" json:"user_entity,omitempty"`
	RoleEntity  *milvuspb.RoleEntity         `protobuf:"bytes,3,opt,name=role_entity,json=roleEntity,proto3" json:"role_entity,omitempty"`
	OperateType milvuspb.OperateUserRoleType `protobuf:"varint,4,opt,name=operate_type,json=operateType,proto3,enum=milvus.proto.milvus.OperateUserRoleType" json:"operate_type,omitempty"`
}

func (x *OperateUserRoleRequest) Reset() {
	*x = OperateUserRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateUserRoleRequest) ProtoMessage() {}

func (x *OperateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*OperateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{6}
}

func (x *OperateUserRoleRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *OperateUserRoleRequest) GetUserEntity() *milvuspb.UserEntity {
	if x != nil {
		return x.UserEntity
	}
	return nil
}

func (x *OperateUserRoleRequest) GetRoleEntity() *milvuspb.RoleEntity {
	if x != nil {
		return x.RoleEntity
	}
	return nil
}

func (x *OperateUserRoleRequest) GetOperateType() milvuspb.OperateUserRoleType {
	if x != nil {
		return x.OperateType
	}
	return milvuspb.OperateUserRoleType(0)
}

type OperateUserRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *OperateUserRoleResponse) Reset() {
	*x = OperateUserRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateUserRoleResponse) ProtoMessage() {}

func (x *OperateUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateUserRoleResponse.ProtoReflect.Descriptor instead.
func (*OperateUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{7}
}

func (x *OperateUserRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// SelectRole
type SelectRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant          string               `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Entity          *milvuspb.RoleEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	IncludeUserInfo bool                 `protobuf:"varint,3,opt,name=include_user_info,json=includeUserInfo,proto3" json:"include_user_info,omitempty"`
}

func (x *SelectRoleRequest) Reset() {
	*x = SelectRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRoleRequest) ProtoMessage() {}

func (x *SelectRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRoleRequest.ProtoReflect.Descriptor instead.
func (*SelectRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{8}
}

func (x *SelectRoleRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *SelectRoleRequest) GetEntity() *milvuspb.RoleEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *SelectRoleRequest) GetIncludeUserInfo() bool {
	if x != nil {
		return x.IncludeUserInfo
	}
	return false
}

type SelectRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Results []*milvuspb.RoleResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SelectRoleResponse) Reset() {
	*x = SelectRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRoleResponse) ProtoMessage() {}

func (x *SelectRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRoleResponse.ProtoReflect.Descriptor instead.
func (*SelectRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{9}
}

func (x *SelectRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SelectRoleResponse) GetResults() []*milvuspb.RoleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// SelectUser
type SelectUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant          string               `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Entity          *milvuspb.UserEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	IncludeRoleInfo bool                 `protobuf:"varint,3,opt,name=include_role_info,json=includeRoleInfo,proto3" json:"include_role_info,omitempty"`
}

func (x *SelectUserRequest) Reset() {
	*x = SelectUserRequest{}
	mi := &file_catalog_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectUserRequest) ProtoMessage() {}

func (x *SelectUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectUserRequest.ProtoReflect.Descriptor instead.
func (*SelectUserRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{10}
}

func (x *SelectUserRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *SelectUserRequest) GetEntity() *milvuspb.UserEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *SelectUserRequest) GetIncludeRoleInfo() bool {
	if x != nil {
		return x.IncludeRoleInfo
	}
	return false
}

type SelectUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Results []*milvuspb.UserResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SelectUserResponse) Reset() {
	*x = SelectUserResponse{}
	mi := &file_catalog_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectUserResponse) ProtoMessage() {}

func (x *SelectUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectUserResponse.ProtoReflect.Descriptor instead.
func (*SelectUserResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{11}
}

func (x *SelectUserResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SelectUserResponse) GetResults() []*milvuspb.UserResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// ListUserRole
type ListUserRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (x *ListUserRoleRequest) Reset() {
	*x = ListUserRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoleRequest) ProtoMessage() {}

func (x *ListUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoleRequest.ProtoReflect.Descriptor instead.
func (*ListUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserRoleRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListUserRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UserRoles []string         `protobuf:"bytes,2,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
}

func (x *ListUserRoleResponse) Reset() {
	*x = ListUserRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoleResponse) ProtoMessage() {}

func (x *ListUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoleResponse.ProtoReflect.Descriptor instead.
func (*ListUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListUserRoleResponse) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

// CheckIfCreateRole — carries the original milvuspb request.
type CheckIfCreateRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.CreateRoleRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfCreateRoleRequest) Reset() {
	*x = CheckIfCreateRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfCreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfCreateRoleRequest) ProtoMessage() {}

func (x *CheckIfCreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfCreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CheckIfCreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{14}
}

func (x *CheckIfCreateRoleRequest) GetReq() *milvuspb.CreateRoleRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfCreateRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfCreateRoleResponse) Reset() {
	*x = CheckIfCreateRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfCreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfCreateRoleResponse) ProtoMessage() {}

func (x *CheckIfCreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfCreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CheckIfCreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{15}
}

func (x *CheckIfCreateRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// CheckIfAlterRole
type CheckIfAlterRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.AlterRoleRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfAlterRoleRequest) Reset() {
	*x = CheckIfAlterRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAlterRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAlterRoleRequest) ProtoMessage() {}

func (x *CheckIfAlterRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAlterRoleRequest.ProtoReflect.Descriptor instead.
func (*CheckIfAlterRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{16}
}

func (x *CheckIfAlterRoleRequest) GetReq() *milvuspb.AlterRoleRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfAlterRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfAlterRoleResponse) Reset() {
	*x = CheckIfAlterRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfAlterRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfAlterRoleResponse) ProtoMessage() {}

func (x *CheckIfAlterRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfAlterRoleResponse.ProtoReflect.Descriptor instead.
func (*CheckIfAlterRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{17}
}

func (x *CheckIfAlterRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// CheckIfDropRole
type CheckIfDropRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.DropRoleRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfDropRoleRequest) Reset() {
	*x = CheckIfDropRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDropRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDropRoleRequest) ProtoMessage() {}

func (x *CheckIfDropRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDropRoleRequest.ProtoReflect.Descriptor instead.
func (*CheckIfDropRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{18}
}

func (x *CheckIfDropRoleRequest) GetReq() *milvuspb.DropRoleRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfDropRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfDropRoleResponse) Reset() {
	*x = CheckIfDropRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfDropRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfDropRoleResponse) ProtoMessage() {}

func (x *CheckIfDropRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfDropRoleResponse.ProtoReflect.Descriptor instead.
func (*CheckIfDropRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{19}
}

func (x *CheckIfDropRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// CheckIfOperateUserRole
type CheckIfOperateUserRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.OperateUserRoleRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfOperateUserRoleRequest) Reset() {
	*x = CheckIfOperateUserRoleRequest{}
	mi := &file_catalog_role_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfOperateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfOperateUserRoleRequest) ProtoMessage() {}

func (x *CheckIfOperateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfOperateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*CheckIfOperateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{20}
}

func (x *CheckIfOperateUserRoleRequest) GetReq() *milvuspb.OperateUserRoleRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfOperateUserRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfOperateUserRoleResponse) Reset() {
	*x = CheckIfOperateUserRoleResponse{}
	mi := &file_catalog_role_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfOperateUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfOperateUserRoleResponse) ProtoMessage() {}

func (x *CheckIfOperateUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_role_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfOperateUserRoleResponse.ProtoReflect.Descriptor instead.
func (*CheckIfOperateUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_role_proto_rawDescGZIP(), []int{21}
}

func (x *CheckIfOperateUserRoleResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_catalog_role_proto protoreflect.FileDescriptor

var file_catalog_role_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x49, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x63, 0x0a, 0x10, 0x41, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x48, 0x0a, 0x11,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x46, 0x0a, 0x0f, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47,
	0x0a, 0x10, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x81, 0x02, 0x0a, 0x16, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x0b,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x4b,
	0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x17, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x11,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x84,
	0x01, 0x0a, 0x12, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x11,
	0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22,
	0x2d, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x22, 0x6a,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x18, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71,
	0x22, 0x50, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x52, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x41, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x4f, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49,
	0x66, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x50, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x66, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x36, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x4e, 0x0a, 0x17, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x66, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5e, 0x0a, 0x1d, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x66, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x03, 0x72, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x55, 0x0a, 0x1e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x66, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_role_proto_rawDescOnce sync.Once
	file_catalog_role_proto_rawDescData = file_catalog_role_proto_rawDesc
)

func file_catalog_role_proto_rawDescGZIP() []byte {
	file_catalog_role_proto_rawDescOnce.Do(func() {
		file_catalog_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_role_proto_rawDescData)
	})
	return file_catalog_role_proto_rawDescData
}

var file_catalog_role_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_catalog_role_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),               // 0: milvus.proto.catalog.CreateRoleRequest
	(*CreateRoleResponse)(nil),              // 1: milvus.proto.catalog.CreateRoleResponse
	(*AlterRoleRequest)(nil),                // 2: milvus.proto.catalog.AlterRoleRequest
	(*AlterRoleResponse)(nil),               // 3: milvus.proto.catalog.AlterRoleResponse
	(*DropRoleRequest)(nil),                 // 4: milvus.proto.catalog.DropRoleRequest
	(*DropRoleResponse)(nil),                // 5: milvus.proto.catalog.DropRoleResponse
	(*OperateUserRoleRequest)(nil),          // 6: milvus.proto.catalog.OperateUserRoleRequest
	(*OperateUserRoleResponse)(nil),         // 7: milvus.proto.catalog.OperateUserRoleResponse
	(*SelectRoleRequest)(nil),               // 8: milvus.proto.catalog.SelectRoleRequest
	(*SelectRoleResponse)(nil),              // 9: milvus.proto.catalog.SelectRoleResponse
	(*SelectUserRequest)(nil),               // 10: milvus.proto.catalog.SelectUserRequest
	(*SelectUserResponse)(nil),              // 11: milvus.proto.catalog.SelectUserResponse
	(*ListUserRoleRequest)(nil),             // 12: milvus.proto.catalog.ListUserRoleRequest
	(*ListUserRoleResponse)(nil),            // 13: milvus.proto.catalog.ListUserRoleResponse
	(*CheckIfCreateRoleRequest)(nil),        // 14: milvus.proto.catalog.CheckIfCreateRoleRequest
	(*CheckIfCreateRoleResponse)(nil),       // 15: milvus.proto.catalog.CheckIfCreateRoleResponse
	(*CheckIfAlterRoleRequest)(nil),         // 16: milvus.proto.catalog.CheckIfAlterRoleRequest
	(*CheckIfAlterRoleResponse)(nil),        // 17: milvus.proto.catalog.CheckIfAlterRoleResponse
	(*CheckIfDropRoleRequest)(nil),          // 18: milvus.proto.catalog.CheckIfDropRoleRequest
	(*CheckIfDropRoleResponse)(nil),         // 19: milvus.proto.catalog.CheckIfDropRoleResponse
	(*CheckIfOperateUserRoleRequest)(nil),   // 20: milvus.proto.catalog.CheckIfOperateUserRoleRequest
	(*CheckIfOperateUserRoleResponse)(nil),  // 21: milvus.proto.catalog.CheckIfOperateUserRoleResponse
	(*milvuspb.RoleEntity)(nil),             // 22: milvus.proto.milvus.RoleEntity
	(*commonpb.Status)(nil),                 // 23: milvus.proto.common.Status
	(*milvuspb.UserEntity)(nil),             // 24: milvus.proto.milvus.UserEntity
	(milvuspb.OperateUserRoleType)(0),       // 25: milvus.proto.milvus.OperateUserRoleType
	(*milvuspb.RoleResult)(nil),             // 26: milvus.proto.milvus.RoleResult
	(*milvuspb.UserResult)(nil),             // 27: milvus.proto.milvus.UserResult
	(*milvuspb.CreateRoleRequest)(nil),      // 28: milvus.proto.milvus.CreateRoleRequest
	(*milvuspb.AlterRoleRequest)(nil),       // 29: milvus.proto.milvus.AlterRoleRequest
	(*milvuspb.DropRoleRequest)(nil),        // 30: milvus.proto.milvus.DropRoleRequest
	(*milvuspb.OperateUserRoleRequest)(nil), // 31: milvus.proto.milvus.OperateUserRoleRequest
}
var file_catalog_role_proto_depIdxs = []int32{
	22, // 0: milvus.proto.catalog.CreateRoleRequest.entity:type_name -> milvus.proto.milvus.RoleEntity
	23, // 1: milvus.proto.catalog.CreateRoleResponse.status:type_name -> milvus.proto.common.Status
	22, // 2: milvus.proto.catalog.AlterRoleRequest.entity:type_name -> milvus.proto.milvus.RoleEntity
	23, // 3: milvus.proto.catalog.AlterRoleResponse.status:type_name -> milvus.proto.common.Status
	23, // 4: milvus.proto.catalog.DropRoleResponse.status:type_name -> milvus.proto.common.Status
	24, // 5: milvus.proto.catalog.OperateUserRoleRequest.user_entity:type_name -> milvus.proto.milvus.UserEntity
	22, // 6: milvus.proto.catalog.OperateUserRoleRequest.role_entity:type_name -> milvus.proto.milvus.RoleEntity
	25, // 7: milvus.proto.catalog.OperateUserRoleRequest.operate_type:type_name -> milvus.proto.milvus.OperateUserRoleType
	23, // 8: milvus.proto.catalog.OperateUserRoleResponse.status:type_name -> milvus.proto.common.Status
	22, // 9: milvus.proto.catalog.SelectRoleRequest.entity:type_name -> milvus.proto.milvus.RoleEntity
	23, // 10: milvus.proto.catalog.SelectRoleResponse.status:type_name -> milvus.proto.common.Status
	26, // 11: milvus.proto.catalog.SelectRoleResponse.results:type_name -> milvus.proto.milvus.RoleResult
	24, // 12: milvus.proto.catalog.SelectUserRequest.entity:type_name -> milvus.proto.milvus.UserEntity
	23, // 13: milvus.proto.catalog.SelectUserResponse.status:type_name -> milvus.proto.common.Status
	27, // 14: milvus.proto.catalog.SelectUserResponse.results:type_name -> milvus.proto.milvus.UserResult
	23, // 15: milvus.proto.catalog.ListUserRoleResponse.status:type_name -> milvus.proto.common.Status
	28, // 16: milvus.proto.catalog.CheckIfCreateRoleRequest.req:type_name -> milvus.proto.milvus.CreateRoleRequest
	23, // 17: milvus.proto.catalog.CheckIfCreateRoleResponse.status:type_name -> milvus.proto.common.Status
	29, // 18: milvus.proto.catalog.CheckIfAlterRoleRequest.req:type_name -> milvus.proto.milvus.AlterRoleRequest
	23, // 19: milvus.proto.catalog.CheckIfAlterRoleResponse.status:type_name -> milvus.proto.common.Status
	30, // 20: milvus.proto.catalog.CheckIfDropRoleRequest.req:type_name -> milvus.proto.milvus.DropRoleRequest
	23, // 21: milvus.proto.catalog.CheckIfDropRoleResponse.status:type_name -> milvus.proto.common.Status
	31, // 22: milvus.proto.catalog.CheckIfOperateUserRoleRequest.req:type_name -> milvus.proto.milvus.OperateUserRoleRequest
	23, // 23: milvus.proto.catalog.CheckIfOperateUserRoleResponse.status:type_name -> milvus.proto.common.Status
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_catalog_role_proto_init() }
func file_catalog_role_proto_init() {
	if File_catalog_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_role_proto_goTypes,
		DependencyIndexes: file_catalog_role_proto_depIdxs,
		MessageInfos:      file_catalog_role_proto_msgTypes,
	}.Build()
	File_catalog_role_proto = out.File
	file_catalog_role_proto_rawDesc = nil
	file_catalog_role_proto_goTypes = nil
	file_catalog_role_proto_depIdxs = nil
}
