// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_grant.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	milvuspb "github.com/milvus-io/milvus-proto/go-api/v3/milvuspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatePrivilegeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant      string                        `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Entity      *milvuspb.GrantEntity         `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	OperateType milvuspb.OperatePrivilegeType `protobuf:"varint,3,opt,name=operate_type,json=operateType,proto3,enum=milvus.proto.milvus.OperatePrivilegeType" json:"operate_type,omitempty"`
}

func (x *OperatePrivilegeRequest) Reset() {
	*x = OperatePrivilegeRequest{}
	mi := &file_catalog_grant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatePrivilegeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatePrivilegeRequest) ProtoMessage() {}

func (x *OperatePrivilegeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatePrivilegeRequest.ProtoReflect.Descriptor instead.
func (*OperatePrivilegeRequest) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{0}
}

func (x *OperatePrivilegeRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *OperatePrivilegeRequest) GetEntity() *milvuspb.GrantEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *OperatePrivilegeRequest) GetOperateType() milvuspb.OperatePrivilegeType {
	if x != nil {
		return x.OperateType
	}
	return milvuspb.OperatePrivilegeType(0)
}

type OperatePrivilegeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *OperatePrivilegeResponse) Reset() {
	*x = OperatePrivilegeResponse{}
	mi := &file_catalog_grant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatePrivilegeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatePrivilegeResponse) ProtoMessage() {}

func (x *OperatePrivilegeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatePrivilegeResponse.ProtoReflect.Descriptor instead.
func (*OperatePrivilegeResponse) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{1}
}

func (x *OperatePrivilegeResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DropGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string               `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Role   *milvuspb.RoleEntity `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *DropGrantRequest) Reset() {
	*x = DropGrantRequest{}
	mi := &file_catalog_grant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGrantRequest) ProtoMessage() {}

func (x *DropGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropGrantRequest.ProtoReflect.Descriptor instead.
func (*DropGrantRequest) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{2}
}

func (x *DropGrantRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *DropGrantRequest) GetRole() *milvuspb.RoleEntity {
	if x != nil {
		return x.Role
	}
	return nil
}

type DropGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DropGrantResponse) Reset() {
	*x = DropGrantResponse{}
	mi := &file_catalog_grant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGrantResponse) ProtoMessage() {}

func (x *DropGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropGrantResponse.ProtoReflect.Descriptor instead.
func (*DropGrantResponse) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{3}
}

func (x *DropGrantResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type RestoreRBACRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string             `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Meta   *milvuspb.RBACMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *RestoreRBACRequest) Reset() {
	*x = RestoreRBACRequest{}
	mi := &file_catalog_grant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRBACRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRBACRequest) ProtoMessage() {}

func (x *RestoreRBACRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRBACRequest.ProtoReflect.Descriptor instead.
func (*RestoreRBACRequest) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreRBACRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RestoreRBACRequest) GetMeta() *milvuspb.RBACMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RestoreRBACResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RestoreRBACResponse) Reset() {
	*x = RestoreRBACResponse{}
	mi := &file_catalog_grant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRBACResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRBACResponse) ProtoMessage() {}

func (x *RestoreRBACResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRBACResponse.ProtoReflect.Descriptor instead.
func (*RestoreRBACResponse) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreRBACResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type SelectGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Entity *milvuspb.GrantEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *SelectGrantRequest) Reset() {
	*x = SelectGrantRequest{}
	mi := &file_catalog_grant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectGrantRequest) ProtoMessage() {}

func (x *SelectGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectGrantRequest.ProtoReflect.Descriptor instead.
func (*SelectGrantRequest) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{6}
}

func (x *SelectGrantRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *SelectGrantRequest) GetEntity() *milvuspb.GrantEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type SelectGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *commonpb.Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entities []*milvuspb.GrantEntity `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *SelectGrantResponse) Reset() {
	*x = SelectGrantResponse{}
	mi := &file_catalog_grant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectGrantResponse) ProtoMessage() {}

func (x *SelectGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectGrantResponse.ProtoReflect.Descriptor instead.
func (*SelectGrantResponse) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{7}
}

func (x *SelectGrantResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SelectGrantResponse) GetEntities() []*milvuspb.GrantEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type ListPolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (x *ListPolicyRequest) Reset() {
	*x = ListPolicyRequest{}
	mi := &file_catalog_grant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolicyRequest) ProtoMessage() {}

func (x *ListPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolicyRequest.ProtoReflect.Descriptor instead.
func (*ListPolicyRequest) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{8}
}

func (x *ListPolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListPolicyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *commonpb.Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entities []*milvuspb.GrantEntity `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *ListPolicyResponse) Reset() {
	*x = ListPolicyResponse{}
	mi := &file_catalog_grant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolicyResponse) ProtoMessage() {}

func (x *ListPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolicyResponse.ProtoReflect.Descriptor instead.
func (*ListPolicyResponse) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{9}
}

func (x *ListPolicyResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListPolicyResponse) GetEntities() []*milvuspb.GrantEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type BackupRBACRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (x *BackupRBACRequest) Reset() {
	*x = BackupRBACRequest{}
	mi := &file_catalog_grant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRBACRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRBACRequest) ProtoMessage() {}

func (x *BackupRBACRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRBACRequest.ProtoReflect.Descriptor instead.
func (*BackupRBACRequest) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{10}
}

func (x *BackupRBACRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type BackupRBACResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *commonpb.Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RbacMeta *milvuspb.RBACMeta `protobuf:"bytes,2,opt,name=rbac_meta,json=rbacMeta,proto3" json:"rbac_meta,omitempty"`
}

func (x *BackupRBACResponse) Reset() {
	*x = BackupRBACResponse{}
	mi := &file_catalog_grant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRBACResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRBACResponse) ProtoMessage() {}

func (x *BackupRBACResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRBACResponse.ProtoReflect.Descriptor instead.
func (*BackupRBACResponse) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{11}
}

func (x *BackupRBACResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BackupRBACResponse) GetRbacMeta() *milvuspb.RBACMeta {
	if x != nil {
		return x.RbacMeta
	}
	return nil
}

type CheckIfRBACRestorableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.RestoreRBACMetaRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfRBACRestorableRequest) Reset() {
	*x = CheckIfRBACRestorableRequest{}
	mi := &file_catalog_grant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfRBACRestorableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfRBACRestorableRequest) ProtoMessage() {}

func (x *CheckIfRBACRestorableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfRBACRestorableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfRBACRestorableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{12}
}

func (x *CheckIfRBACRestorableRequest) GetReq() *milvuspb.RestoreRBACMetaRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfRBACRestorableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfRBACRestorableResponse) Reset() {
	*x = CheckIfRBACRestorableResponse{}
	mi := &file_catalog_grant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfRBACRestorableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfRBACRestorableResponse) ProtoMessage() {}

func (x *CheckIfRBACRestorableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_grant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfRBACRestorableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfRBACRestorableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_grant_proto_rawDescGZIP(), []int{13}
}

func (x *CheckIfRBACRestorableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_catalog_grant_proto protoreflect.FileDescriptor

var file_catalog_grant_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x17, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x4c, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x4f, 0x0a, 0x18, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x5f, 0x0a, 0x10, 0x44, 0x72, 0x6f, 0x70, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x12, 0x33, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x48, 0x0a, 0x11, 0x44, 0x72, 0x6f, 0x70, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x5f, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x42, 0x41, 0x43, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x31, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x22, 0x4a, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x42, 0x41, 0x43, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x66, 0x0a, 0x12,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x88, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x3c, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22,
	0x2b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x22, 0x87, 0x01, 0x0a,
	0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x11, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x52, 0x42, 0x41, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x12, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x42,
	0x41, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x3a, 0x0a, 0x09, 0x72, 0x62, 0x61, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x08, 0x72, 0x62, 0x61, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x1c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x52, 0x42, 0x41, 0x43, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x03, 0x72,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x42, 0x41, 0x43, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x54, 0x0a, 0x1d, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x66, 0x52, 0x42, 0x41, 0x43, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_grant_proto_rawDescOnce sync.Once
	file_catalog_grant_proto_rawDescData = file_catalog_grant_proto_rawDesc
)

func file_catalog_grant_proto_rawDescGZIP() []byte {
	file_catalog_grant_proto_rawDescOnce.Do(func() {
		file_catalog_grant_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_grant_proto_rawDescData)
	})
	return file_catalog_grant_proto_rawDescData
}

var file_catalog_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_catalog_grant_proto_goTypes = []any{
	(*OperatePrivilegeRequest)(nil),         // 0: milvus.proto.catalog.OperatePrivilegeRequest
	(*OperatePrivilegeResponse)(nil),        // 1: milvus.proto.catalog.OperatePrivilegeResponse
	(*DropGrantRequest)(nil),                // 2: milvus.proto.catalog.DropGrantRequest
	(*DropGrantResponse)(nil),               // 3: milvus.proto.catalog.DropGrantResponse
	(*RestoreRBACRequest)(nil),              // 4: milvus.proto.catalog.RestoreRBACRequest
	(*RestoreRBACResponse)(nil),             // 5: milvus.proto.catalog.RestoreRBACResponse
	(*SelectGrantRequest)(nil),              // 6: milvus.proto.catalog.SelectGrantRequest
	(*SelectGrantResponse)(nil),             // 7: milvus.proto.catalog.SelectGrantResponse
	(*ListPolicyRequest)(nil),               // 8: milvus.proto.catalog.ListPolicyRequest
	(*ListPolicyResponse)(nil),              // 9: milvus.proto.catalog.ListPolicyResponse
	(*BackupRBACRequest)(nil),               // 10: milvus.proto.catalog.BackupRBACRequest
	(*BackupRBACResponse)(nil),              // 11: milvus.proto.catalog.BackupRBACResponse
	(*CheckIfRBACRestorableRequest)(nil),    // 12: milvus.proto.catalog.CheckIfRBACRestorableRequest
	(*CheckIfRBACRestorableResponse)(nil),   // 13: milvus.proto.catalog.CheckIfRBACRestorableResponse
	(*milvuspb.GrantEntity)(nil),            // 14: milvus.proto.milvus.GrantEntity
	(milvuspb.OperatePrivilegeType)(0),      // 15: milvus.proto.milvus.OperatePrivilegeType
	(*commonpb.Status)(nil),                 // 16: milvus.proto.common.Status
	(*milvuspb.RoleEntity)(nil),             // 17: milvus.proto.milvus.RoleEntity
	(*milvuspb.RBACMeta)(nil),               // 18: milvus.proto.milvus.RBACMeta
	(*milvuspb.RestoreRBACMetaRequest)(nil), // 19: milvus.proto.milvus.RestoreRBACMetaRequest
}
var file_catalog_grant_proto_depIdxs = []int32{
	14, // 0: milvus.proto.catalog.OperatePrivilegeRequest.entity:type_name -> milvus.proto.milvus.GrantEntity
	15, // 1: milvus.proto.catalog.OperatePrivilegeRequest.operate_type:type_name -> milvus.proto.milvus.OperatePrivilegeType
	16, // 2: milvus.proto.catalog.OperatePrivilegeResponse.status:type_name -> milvus.proto.common.Status
	17, // 3: milvus.proto.catalog.DropGrantRequest.role:type_name -> milvus.proto.milvus.RoleEntity
	16, // 4: milvus.proto.catalog.DropGrantResponse.status:type_name -> milvus.proto.common.Status
	18, // 5: milvus.proto.catalog.RestoreRBACRequest.meta:type_name -> milvus.proto.milvus.RBACMeta
	16, // 6: milvus.proto.catalog.RestoreRBACResponse.status:type_name -> milvus.proto.common.Status
	14, // 7: milvus.proto.catalog.SelectGrantRequest.entity:type_name -> milvus.proto.milvus.GrantEntity
	16, // 8: milvus.proto.catalog.SelectGrantResponse.status:type_name -> milvus.proto.common.Status
	14, // 9: milvus.proto.catalog.SelectGrantResponse.entities:type_name -> milvus.proto.milvus.GrantEntity
	16, // 10: milvus.proto.catalog.ListPolicyResponse.status:type_name -> milvus.proto.common.Status
	14, // 11: milvus.proto.catalog.ListPolicyResponse.entities:type_name -> milvus.proto.milvus.GrantEntity
	16, // 12: milvus.proto.catalog.BackupRBACResponse.status:type_name -> milvus.proto.common.Status
	18, // 13: milvus.proto.catalog.BackupRBACResponse.rbac_meta:type_name -> milvus.proto.milvus.RBACMeta
	19, // 14: milvus.proto.catalog.CheckIfRBACRestorableRequest.req:type_name -> milvus.proto.milvus.RestoreRBACMetaRequest
	16, // 15: milvus.proto.catalog.CheckIfRBACRestorableResponse.status:type_name -> milvus.proto.common.Status
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_catalog_grant_proto_init() }
func file_catalog_grant_proto_init() {
	if File_catalog_grant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_grant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_grant_proto_goTypes,
		DependencyIndexes: file_catalog_grant_proto_depIdxs,
		MessageInfos:      file_catalog_grant_proto_msgTypes,
	}.Build()
	File_catalog_grant_proto = out.File
	file_catalog_grant_proto_rawDesc = nil
	file_catalog_grant_proto_goTypes = nil
	file_catalog_grant_proto_depIdxs = nil
}
