// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: catalog_privilegegroup.proto

package catalogpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	milvuspb "github.com/milvus-io/milvus-proto/go-api/v3/milvuspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePrivilegeGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *CreatePrivilegeGroupRequest) Reset() {
	*x = CreatePrivilegeGroupRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivilegeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivilegeGroupRequest) ProtoMessage() {}

func (x *CreatePrivilegeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivilegeGroupRequest.ProtoReflect.Descriptor instead.
func (*CreatePrivilegeGroupRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePrivilegeGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type CreatePrivilegeGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreatePrivilegeGroupResponse) Reset() {
	*x = CreatePrivilegeGroupResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivilegeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivilegeGroupResponse) ProtoMessage() {}

func (x *CreatePrivilegeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivilegeGroupResponse.ProtoReflect.Descriptor instead.
func (*CreatePrivilegeGroupResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePrivilegeGroupResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DropPrivilegeGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *DropPrivilegeGroupRequest) Reset() {
	*x = DropPrivilegeGroupRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropPrivilegeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropPrivilegeGroupRequest) ProtoMessage() {}

func (x *DropPrivilegeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropPrivilegeGroupRequest.ProtoReflect.Descriptor instead.
func (*DropPrivilegeGroupRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{2}
}

func (x *DropPrivilegeGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type DropPrivilegeGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DropPrivilegeGroupResponse) Reset() {
	*x = DropPrivilegeGroupResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropPrivilegeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropPrivilegeGroupResponse) ProtoMessage() {}

func (x *DropPrivilegeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropPrivilegeGroupResponse.ProtoReflect.Descriptor instead.
func (*DropPrivilegeGroupResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{3}
}

func (x *DropPrivilegeGroupResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type OperatePrivilegeGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName   string                             `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Privileges  []*milvuspb.PrivilegeEntity        `protobuf:"bytes,2,rep,name=privileges,proto3" json:"privileges,omitempty"`
	OperateType milvuspb.OperatePrivilegeGroupType `protobuf:"varint,3,opt,name=operate_type,json=operateType,proto3,enum=milvus.proto.milvus.OperatePrivilegeGroupType" json:"operate_type,omitempty"`
}

func (x *OperatePrivilegeGroupRequest) Reset() {
	*x = OperatePrivilegeGroupRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatePrivilegeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatePrivilegeGroupRequest) ProtoMessage() {}

func (x *OperatePrivilegeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatePrivilegeGroupRequest.ProtoReflect.Descriptor instead.
func (*OperatePrivilegeGroupRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{4}
}

func (x *OperatePrivilegeGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *OperatePrivilegeGroupRequest) GetPrivileges() []*milvuspb.PrivilegeEntity {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *OperatePrivilegeGroupRequest) GetOperateType() milvuspb.OperatePrivilegeGroupType {
	if x != nil {
		return x.OperateType
	}
	return milvuspb.OperatePrivilegeGroupType(0)
}

type OperatePrivilegeGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *OperatePrivilegeGroupResponse) Reset() {
	*x = OperatePrivilegeGroupResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatePrivilegeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatePrivilegeGroupResponse) ProtoMessage() {}

func (x *OperatePrivilegeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatePrivilegeGroupResponse.ProtoReflect.Descriptor instead.
func (*OperatePrivilegeGroupResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{5}
}

func (x *OperatePrivilegeGroupResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type IsCustomPrivilegeGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *IsCustomPrivilegeGroupRequest) Reset() {
	*x = IsCustomPrivilegeGroupRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCustomPrivilegeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCustomPrivilegeGroupRequest) ProtoMessage() {}

func (x *IsCustomPrivilegeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCustomPrivilegeGroupRequest.ProtoReflect.Descriptor instead.
func (*IsCustomPrivilegeGroupRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{6}
}

func (x *IsCustomPrivilegeGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type IsCustomPrivilegeGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsCustom bool             `protobuf:"varint,2,opt,name=is_custom,json=isCustom,proto3" json:"is_custom,omitempty"`
}

func (x *IsCustomPrivilegeGroupResponse) Reset() {
	*x = IsCustomPrivilegeGroupResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCustomPrivilegeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCustomPrivilegeGroupResponse) ProtoMessage() {}

func (x *IsCustomPrivilegeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCustomPrivilegeGroupResponse.ProtoReflect.Descriptor instead.
func (*IsCustomPrivilegeGroupResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{7}
}

func (x *IsCustomPrivilegeGroupResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *IsCustomPrivilegeGroupResponse) GetIsCustom() bool {
	if x != nil {
		return x.IsCustom
	}
	return false
}

type ListPrivilegeGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPrivilegeGroupsRequest) Reset() {
	*x = ListPrivilegeGroupsRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivilegeGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivilegeGroupsRequest) ProtoMessage() {}

func (x *ListPrivilegeGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivilegeGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListPrivilegeGroupsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{8}
}

type ListPrivilegeGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status          *commonpb.Status               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PrivilegeGroups []*milvuspb.PrivilegeGroupInfo `protobuf:"bytes,2,rep,name=privilege_groups,json=privilegeGroups,proto3" json:"privilege_groups,omitempty"`
}

func (x *ListPrivilegeGroupsResponse) Reset() {
	*x = ListPrivilegeGroupsResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivilegeGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivilegeGroupsResponse) ProtoMessage() {}

func (x *ListPrivilegeGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivilegeGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListPrivilegeGroupsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{9}
}

func (x *ListPrivilegeGroupsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListPrivilegeGroupsResponse) GetPrivilegeGroups() []*milvuspb.PrivilegeGroupInfo {
	if x != nil {
		return x.PrivilegeGroups
	}
	return nil
}

type GetPrivilegeGroupRolesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *GetPrivilegeGroupRolesRequest) Reset() {
	*x = GetPrivilegeGroupRolesRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivilegeGroupRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivilegeGroupRolesRequest) ProtoMessage() {}

func (x *GetPrivilegeGroupRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivilegeGroupRolesRequest.ProtoReflect.Descriptor instead.
func (*GetPrivilegeGroupRolesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{10}
}

func (x *GetPrivilegeGroupRolesRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type GetPrivilegeGroupRolesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Roles  []*milvuspb.RoleEntity `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *GetPrivilegeGroupRolesResponse) Reset() {
	*x = GetPrivilegeGroupRolesResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivilegeGroupRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivilegeGroupRolesResponse) ProtoMessage() {}

func (x *GetPrivilegeGroupRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivilegeGroupRolesResponse.ProtoReflect.Descriptor instead.
func (*GetPrivilegeGroupRolesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{11}
}

func (x *GetPrivilegeGroupRolesResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetPrivilegeGroupRolesResponse) GetRoles() []*milvuspb.RoleEntity {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CheckIfPrivilegeGroupCreatableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.CreatePrivilegeGroupRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfPrivilegeGroupCreatableRequest) Reset() {
	*x = CheckIfPrivilegeGroupCreatableRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfPrivilegeGroupCreatableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfPrivilegeGroupCreatableRequest) ProtoMessage() {}

func (x *CheckIfPrivilegeGroupCreatableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfPrivilegeGroupCreatableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfPrivilegeGroupCreatableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{12}
}

func (x *CheckIfPrivilegeGroupCreatableRequest) GetReq() *milvuspb.CreatePrivilegeGroupRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfPrivilegeGroupCreatableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfPrivilegeGroupCreatableResponse) Reset() {
	*x = CheckIfPrivilegeGroupCreatableResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfPrivilegeGroupCreatableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfPrivilegeGroupCreatableResponse) ProtoMessage() {}

func (x *CheckIfPrivilegeGroupCreatableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfPrivilegeGroupCreatableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfPrivilegeGroupCreatableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{13}
}

func (x *CheckIfPrivilegeGroupCreatableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckIfPrivilegeGroupAlterableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.OperatePrivilegeGroupRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfPrivilegeGroupAlterableRequest) Reset() {
	*x = CheckIfPrivilegeGroupAlterableRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfPrivilegeGroupAlterableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfPrivilegeGroupAlterableRequest) ProtoMessage() {}

func (x *CheckIfPrivilegeGroupAlterableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfPrivilegeGroupAlterableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfPrivilegeGroupAlterableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{14}
}

func (x *CheckIfPrivilegeGroupAlterableRequest) GetReq() *milvuspb.OperatePrivilegeGroupRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfPrivilegeGroupAlterableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfPrivilegeGroupAlterableResponse) Reset() {
	*x = CheckIfPrivilegeGroupAlterableResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfPrivilegeGroupAlterableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfPrivilegeGroupAlterableResponse) ProtoMessage() {}

func (x *CheckIfPrivilegeGroupAlterableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfPrivilegeGroupAlterableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfPrivilegeGroupAlterableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{15}
}

func (x *CheckIfPrivilegeGroupAlterableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckIfPrivilegeGroupDropableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *milvuspb.DropPrivilegeGroupRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *CheckIfPrivilegeGroupDropableRequest) Reset() {
	*x = CheckIfPrivilegeGroupDropableRequest{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfPrivilegeGroupDropableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfPrivilegeGroupDropableRequest) ProtoMessage() {}

func (x *CheckIfPrivilegeGroupDropableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfPrivilegeGroupDropableRequest.ProtoReflect.Descriptor instead.
func (*CheckIfPrivilegeGroupDropableRequest) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{16}
}

func (x *CheckIfPrivilegeGroupDropableRequest) GetReq() *milvuspb.DropPrivilegeGroupRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type CheckIfPrivilegeGroupDropableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckIfPrivilegeGroupDropableResponse) Reset() {
	*x = CheckIfPrivilegeGroupDropableResponse{}
	mi := &file_catalog_privilegegroup_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfPrivilegeGroupDropableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfPrivilegeGroupDropableResponse) ProtoMessage() {}

func (x *CheckIfPrivilegeGroupDropableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_privilegegroup_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfPrivilegeGroupDropableResponse.ProtoReflect.Descriptor instead.
func (*CheckIfPrivilegeGroupDropableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_privilegegroup_proto_rawDescGZIP(), []int{17}
}

func (x *CheckIfPrivilegeGroupDropableResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_catalog_privilegegroup_proto protoreflect.FileDescriptor

var file_catalog_privilegegroup_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c,
	0x65, 0x67, 0x65, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0c, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3c, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c,
	0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x53,
	0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x3a, 0x0a, 0x19, 0x44, 0x72, 0x6f, 0x70, 0x50, 0x72, 0x69, 0x76, 0x69,
	0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x51, 0x0a, 0x1a, 0x44, 0x72, 0x6f, 0x70, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xd6, 0x01, 0x0a, 0x1c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x44, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x50, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x73, 0x12, 0x51, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69,
	0x6c, 0x76, 0x75, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76,
	0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x54, 0x0a, 0x1d, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x3e, 0x0a, 0x1d, 0x49, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x72, 0x0a, 0x1e, 0x49, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x22, 0x1c, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x76,
	0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x52, 0x0a, 0x10, 0x70, 0x72, 0x69, 0x76,
	0x69, 0x6c, 0x65, 0x67, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65,
	0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x70, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x3e, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8c, 0x01, 0x0a,
	0x1e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x35, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x25, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x5d, 0x0a, 0x26, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x49, 0x66, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6c, 0x0a, 0x25, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x66, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x43, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69,
	0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x5d, 0x0a, 0x26, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66,
	0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x6c,
	0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x68, 0x0a, 0x24, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x50,
	0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x72, 0x6f,
	0x70, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x03,
	0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x69, 0x6c, 0x76,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x44, 0x72, 0x6f, 0x70, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x5c,
	0x0a, 0x25, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65,
	0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x72, 0x6f, 0x70, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75,
	0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_privilegegroup_proto_rawDescOnce sync.Once
	file_catalog_privilegegroup_proto_rawDescData = file_catalog_privilegegroup_proto_rawDesc
)

func file_catalog_privilegegroup_proto_rawDescGZIP() []byte {
	file_catalog_privilegegroup_proto_rawDescOnce.Do(func() {
		file_catalog_privilegegroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_privilegegroup_proto_rawDescData)
	})
	return file_catalog_privilegegroup_proto_rawDescData
}

var file_catalog_privilegegroup_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_catalog_privilegegroup_proto_goTypes = []any{
	(*CreatePrivilegeGroupRequest)(nil),            // 0: milvus.proto.catalog.CreatePrivilegeGroupRequest
	(*CreatePrivilegeGroupResponse)(nil),           // 1: milvus.proto.catalog.CreatePrivilegeGroupResponse
	(*DropPrivilegeGroupRequest)(nil),              // 2: milvus.proto.catalog.DropPrivilegeGroupRequest
	(*DropPrivilegeGroupResponse)(nil),             // 3: milvus.proto.catalog.DropPrivilegeGroupResponse
	(*OperatePrivilegeGroupRequest)(nil),           // 4: milvus.proto.catalog.OperatePrivilegeGroupRequest
	(*OperatePrivilegeGroupResponse)(nil),          // 5: milvus.proto.catalog.OperatePrivilegeGroupResponse
	(*IsCustomPrivilegeGroupRequest)(nil),          // 6: milvus.proto.catalog.IsCustomPrivilegeGroupRequest
	(*IsCustomPrivilegeGroupResponse)(nil),         // 7: milvus.proto.catalog.IsCustomPrivilegeGroupResponse
	(*ListPrivilegeGroupsRequest)(nil),             // 8: milvus.proto.catalog.ListPrivilegeGroupsRequest
	(*ListPrivilegeGroupsResponse)(nil),            // 9: milvus.proto.catalog.ListPrivilegeGroupsResponse
	(*GetPrivilegeGroupRolesRequest)(nil),          // 10: milvus.proto.catalog.GetPrivilegeGroupRolesRequest
	(*GetPrivilegeGroupRolesResponse)(nil),         // 11: milvus.proto.catalog.GetPrivilegeGroupRolesResponse
	(*CheckIfPrivilegeGroupCreatableRequest)(nil),  // 12: milvus.proto.catalog.CheckIfPrivilegeGroupCreatableRequest
	(*CheckIfPrivilegeGroupCreatableResponse)(nil), // 13: milvus.proto.catalog.CheckIfPrivilegeGroupCreatableResponse
	(*CheckIfPrivilegeGroupAlterableRequest)(nil),  // 14: milvus.proto.catalog.CheckIfPrivilegeGroupAlterableRequest
	(*CheckIfPrivilegeGroupAlterableResponse)(nil), // 15: milvus.proto.catalog.CheckIfPrivilegeGroupAlterableResponse
	(*CheckIfPrivilegeGroupDropableRequest)(nil),   // 16: milvus.proto.catalog.CheckIfPrivilegeGroupDropableRequest
	(*CheckIfPrivilegeGroupDropableResponse)(nil),  // 17: milvus.proto.catalog.CheckIfPrivilegeGroupDropableResponse
	(*commonpb.Status)(nil),                        // 18: milvus.proto.common.Status
	(*milvuspb.PrivilegeEntity)(nil),               // 19: milvus.proto.milvus.PrivilegeEntity
	(milvuspb.OperatePrivilegeGroupType)(0),        // 20: milvus.proto.milvus.OperatePrivilegeGroupType
	(*milvuspb.PrivilegeGroupInfo)(nil),            // 21: milvus.proto.milvus.PrivilegeGroupInfo
	(*milvuspb.RoleEntity)(nil),                    // 22: milvus.proto.milvus.RoleEntity
	(*milvuspb.CreatePrivilegeGroupRequest)(nil),   // 23: milvus.proto.milvus.CreatePrivilegeGroupRequest
	(*milvuspb.OperatePrivilegeGroupRequest)(nil),  // 24: milvus.proto.milvus.OperatePrivilegeGroupRequest
	(*milvuspb.DropPrivilegeGroupRequest)(nil),     // 25: milvus.proto.milvus.DropPrivilegeGroupRequest
}
var file_catalog_privilegegroup_proto_depIdxs = []int32{
	18, // 0: milvus.proto.catalog.CreatePrivilegeGroupResponse.status:type_name -> milvus.proto.common.Status
	18, // 1: milvus.proto.catalog.DropPrivilegeGroupResponse.status:type_name -> milvus.proto.common.Status
	19, // 2: milvus.proto.catalog.OperatePrivilegeGroupRequest.privileges:type_name -> milvus.proto.milvus.PrivilegeEntity
	20, // 3: milvus.proto.catalog.OperatePrivilegeGroupRequest.operate_type:type_name -> milvus.proto.milvus.OperatePrivilegeGroupType
	18, // 4: milvus.proto.catalog.OperatePrivilegeGroupResponse.status:type_name -> milvus.proto.common.Status
	18, // 5: milvus.proto.catalog.IsCustomPrivilegeGroupResponse.status:type_name -> milvus.proto.common.Status
	18, // 6: milvus.proto.catalog.ListPrivilegeGroupsResponse.status:type_name -> milvus.proto.common.Status
	21, // 7: milvus.proto.catalog.ListPrivilegeGroupsResponse.privilege_groups:type_name -> milvus.proto.milvus.PrivilegeGroupInfo
	18, // 8: milvus.proto.catalog.GetPrivilegeGroupRolesResponse.status:type_name -> milvus.proto.common.Status
	22, // 9: milvus.proto.catalog.GetPrivilegeGroupRolesResponse.roles:type_name -> milvus.proto.milvus.RoleEntity
	23, // 10: milvus.proto.catalog.CheckIfPrivilegeGroupCreatableRequest.req:type_name -> milvus.proto.milvus.CreatePrivilegeGroupRequest
	18, // 11: milvus.proto.catalog.CheckIfPrivilegeGroupCreatableResponse.status:type_name -> milvus.proto.common.Status
	24, // 12: milvus.proto.catalog.CheckIfPrivilegeGroupAlterableRequest.req:type_name -> milvus.proto.milvus.OperatePrivilegeGroupRequest
	18, // 13: milvus.proto.catalog.CheckIfPrivilegeGroupAlterableResponse.status:type_name -> milvus.proto.common.Status
	25, // 14: milvus.proto.catalog.CheckIfPrivilegeGroupDropableRequest.req:type_name -> milvus.proto.milvus.DropPrivilegeGroupRequest
	18, // 15: milvus.proto.catalog.CheckIfPrivilegeGroupDropableResponse.status:type_name -> milvus.proto.common.Status
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_catalog_privilegegroup_proto_init() }
func file_catalog_privilegegroup_proto_init() {
	if File_catalog_privilegegroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_privilegegroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_privilegegroup_proto_goTypes,
		DependencyIndexes: file_catalog_privilegegroup_proto_depIdxs,
		MessageInfos:      file_catalog_privilegegroup_proto_msgTypes,
	}.Build()
	File_catalog_privilegegroup_proto = out.File
	file_catalog_privilegegroup_proto_rawDesc = nil
	file_catalog_privilegegroup_proto_goTypes = nil
	file_catalog_privilegegroup_proto_depIdxs = nil
}
