// Command genrouting generates routing_meta_gen.go: a delegating routingMetaTable method for
// every method of rootcoord.IMetaTable. routingMetaTable must implement the WHOLE interface
// (each method resolves the per-namespace MetaTable from the request context and forwards the
// call); hand-writing ~80 near-identical wrappers is error-prone and was the source of a
// nil-pointer panic (only the Database methods were written, the rest fell through to a nil
// embedded interface). This generator + the `var _ rootcoord.IMetaTable` assertion in
// routing_meta.go turn "forgot to route a method" from a runtime panic into a compile error.
//
// Run via `go generate ./internal/catalogservice/...` (working dir = internal/catalogservice).
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"regexp"
	"strings"
)

var fset = token.NewFileSet()

// typeStr renders a type expression, qualifying the two rootcoord-local aliases (UniqueID,
// Timestamp) so the generated code compiles in package catalogservice.
func typeStr(e ast.Expr) string {
	var b bytes.Buffer
	printer.Fprint(&b, fset, e)
	s := b.String()
	s = regexp.MustCompile(`\bUniqueID\b`).ReplaceAllString(s, "typeutil.UniqueID")
	s = regexp.MustCompile(`\bTimestamp\b`).ReplaceAllString(s, "typeutil.Timestamp")
	s = strings.ReplaceAll(s, "typeutil.typeutil.", "typeutil.") // undo double-prefix on already-qualified types
	return s
}

func collect(file string, ifaces map[string]bool, out *[]*ast.Field) {
	f, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		panic(err)
	}
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || !ifaces[ts.Name.Name] {
			return true
		}
		it, ok := ts.Type.(*ast.InterfaceType)
		if !ok {
			return true
		}
		for _, m := range it.Methods.List {
			if len(m.Names) == 0 {
				continue // embedded interface name; its own methods are collected separately
			}
			*out = append(*out, m)
		}
		return true
	})
}

func main() {
	// Working dir is internal/catalogservice (go:generate runs in the package dir).
	const rootcoordDir = "../rootcoord/"
	const outFile = "routing_meta_gen.go"

	var methods []*ast.Field
	ifaces := map[string]bool{"RBACChecker": true, "MetaTableChecker": true, "IMetaTable": true}
	collect(rootcoordDir+"meta_rbac.go", ifaces, &methods)
	collect(rootcoordDir+"meta_table.go", ifaces, &methods)

	seen := map[string]bool{}
	var b strings.Builder
	b.WriteString("// Code generated by genrouting. DO NOT EDIT.\n")
	b.WriteString("package catalogservice\n\nimport (\n\t\"context\"\n\n")
	b.WriteString("\t\"github.com/milvus-io/milvus-proto/go-api/v3/milvuspb\"\n")
	b.WriteString("\t\"github.com/milvus-io/milvus/internal/metastore/model\"\n")
	b.WriteString("\t\"github.com/milvus-io/milvus/pkg/v3/proto/internalpb\"\n")
	b.WriteString("\t\"github.com/milvus-io/milvus/pkg/v3/proto/rootcoordpb\"\n")
	b.WriteString("\t\"github.com/milvus-io/milvus/pkg/v3/streaming/util/message\"\n")
	b.WriteString("\t\"github.com/milvus-io/milvus/pkg/v3/util/typeutil\"\n)\n\n")

	for _, m := range methods {
		name := m.Names[0].Name
		if seen[name] {
			continue
		}
		seen[name] = true
		ft := m.Type.(*ast.FuncType)

		// params: render with names, collect arg names, find the ctx to resolve against.
		var pstr, argNames []string
		ctxArg := "context.Background()"
		pi := 0
		for _, p := range ft.Params.List {
			ts := typeStr(p.Type)
			if len(p.Names) == 0 {
				nm := fmt.Sprintf("a%d", pi)
				pi++
				pstr = append(pstr, nm+" "+ts)
				argNames = append(argNames, nm)
				if ts == "context.Context" {
					ctxArg = nm
				}
				continue
			}
			var ns []string
			for _, id := range p.Names {
				ns = append(ns, id.Name)
				argNames = append(argNames, id.Name)
				if ts == "context.Context" {
					ctxArg = id.Name
				}
				pi++
			}
			pstr = append(pstr, strings.Join(ns, ", ")+" "+ts)
		}

		// results: named (res0..) so the resolve-error path can naked-return zero values;
		// remember the trailing error result's name so we can set it to the resolve error.
		var resDecl []string
		hasResults, hasErr := false, false
		errName := ""
		if ft.Results != nil {
			ri := 0
			for _, r := range ft.Results.List {
				ts := typeStr(r.Type)
				n := 1 // anonymous result = 1
				if len(r.Names) >= 1 {
					n = len(r.Names) // `a, b T` shares one Field with several names
				}
				for k := 0; k < n; k++ {
					rn := fmt.Sprintf("res%d", ri)
					ri++
					resDecl = append(resDecl, rn+" "+ts)
					hasResults = true
					if ts == "error" {
						hasErr = true
						errName = rn
					}
				}
			}
		}
		retSig := ""
		if hasResults {
			retSig = " (" + strings.Join(resDecl, ", ") + ")"
		}

		fmt.Fprintf(&b, "func (r *routingMetaTable) %s(%s)%s {\n", name, strings.Join(pstr, ", "), retSig)
		b.WriteString("\tm, rerr := r.resolve(" + ctxArg + ")\n\tif rerr != nil {\n")
		if hasErr {
			b.WriteString("\t\t" + errName + " = rerr\n")
		}
		b.WriteString("\t\treturn\n\t}\n")
		call := fmt.Sprintf("m.%s(%s)", name, strings.Join(argNames, ", "))
		if hasResults {
			b.WriteString("\treturn " + call + "\n")
		} else {
			b.WriteString("\t" + call + "\n")
		}
		b.WriteString("}\n\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("genrouting: generated %d methods into %s\n", len(seen), outFile)
}
